### ISSUE TITLE
skip_zero_grad_fields=['density', 'k0']参数含义

### ISSUE THREAD

**Issue by mabaorui** [dvlab-research/BlockNeRFPytorch#100]
您好，
   感谢您出色的工作！请问配置文件中‘skip_zero_grad_fields=['density', 'k0']’这一行参数是什么含义，他起什么作用，怎么设置比较好？
   再次感谢您的付出和工作。

**Comment by sjtuytc** [comment]
感谢你的关注和评价。我刚搜索了一下，应该是masked adam里面设置不同优化方案的参数。具体可以看masked Adam.py

**Comment by mabaorui** [comment]
谢谢回复！我也关注到了adam.py文件，这部分代码的意思是如果是skip_zero_grad_fields使用的是adam_upd_cuda.masked_adam_upd优化器，其余的使用另外两个优化器，请问masked_adam_upd优化器和其他两个优化器具体有什么区别嘛？谢谢！
![image](https://user-images.githubusercontent.com/14806520/229263751-c403d684-e2d7-4e73-affb-4d77d0552e58.png)

**Comment by sjtuytc** [comment]
这块我们follow的是dvgov2，你可以读读他们论文中的描述

**Comment by mabaorui** [comment]
好的，非常感谢！
