### ISSUE TITLE
使用默认设置训练block-nerf但是指标极低

### ISSUE THREAD

**Issue by Bin-ze** [dvlab-research/BlockNeRFPytorch#101]
我使用默认设置以及您提供的小的数据集训练block-nerf，但是从训练开始到训练结束，指标几乎没有什么增长，日志如下：

      (large-scale-nerf) guozebin@localhost:~/work_code/LargeScaleNeRFPytorch$ ./scripts/block_nerf_train.sh 0
      Warning, this old implementation of BlockNeRF will be deprecated in the next version!
      /home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py:20: LightningDeprecationWarning: The `pl.plugins.training_type.ddp.DDPPlugin` is de
      precated in v1.6 and will be removed in v1.8. Use `pl.strategies.ddp.DDPStrategy` instead.
        rank_zero_deprecation(
      Using 16bit native Automatic Mixed Precision (AMP)
      GPU available: True, used: True
      TPU available: False, using: 0 TPU cores
      IPU available: False, using: 0 IPUs
      HPU available: False, using: 0 HPUs
      Warning, this old implementation of BlockNeRF will be deprecated in the next version!
      Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
      Warning, this old implementation of BlockNeRF will be deprecated in the next version!
      Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
      Warning, this old implementation of BlockNeRF will be deprecated in the next version!
      Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
      Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
      ----------------------------------------------------------------------------------------------------
      distributed_backend=nccl
      All distributed processes registered. Starting with 4 processes
      ----------------------------------------------------------------------------------------------------
      
      Loading the image...
        0%|▏                                                                                                                                                                        | 1/893 [00:00<01:56,  7.68it/s]Loading the image...
        0%|                                                                                                                                                                                 | 0/893 [00:00<?, ?it/s]Loading the image...
        0%|                                                                                                                                                                                 | 0/893 [00:00<?, ?it/s]Loading the image...
      100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 893/893 [14:56<00:00,  1.00s/it] 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 885/893 [15:43<00:09,  1.19s/it]
      Has  totally loaded 893 images and 71460752 rays!
      100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 893/893 [15:45<00:00,  1.06s/it]
      100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 893/893 [15:47<00:00,  1.06s/it]100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 893/893 [15:48<00:00,  1.06s/it]
      Has  totally loaded 893 images and 71460752 rays!
      Has  totally loaded 893 images and 71460752 rays!
      Has  totally loaded 893 images and 71460752 rays!
      LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
      LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
      LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
      LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
      
        | Name                 | Type              | Params
      -----------------------------------------------------------
      0 | loss                 | BlockNeRFLoss     | 0
      1 | xyz_IPE              | InterPosEmbedding | 0
      2 | dir_exposure_PE      | PosEmbedding      | 0
      3 | embedding_appearance | Embedding         | 48.0 K
      4 | Block_NeRF           | Block_NeRF        | 650 K
      5 | Visibility           | Visibility        | 65.2 K
      -----------------------------------------------------------
      763 K     Trainable params
      0         Non-trainable params
      763 K     Total params
      1.527     Total estimated model params size (MB)
      Sanity Checking: 0it [00:00, ?it/s]Basic image is 709385760
      Basic image is 2099498160
      Sanity Checking DataLoader 0:   0%|                                                                                                                                                     | 0/1 [00:01<?, ?it/s]
      Basic image is 482285680
      Basic image is 943742040
      Basic image is 1970097420
      Basic image is 709385760
      Basic image is 1970097420
      Basic image is 943742040
      2023-04-01 11:41:14.358080: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in
       performance-critical operations:  AVX2 AVX512F FMA
      To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
      2023-04-01 11:41:15.651044: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object
       file: No such file or directory; LD_LIBRARY_PATH: /home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/cv2/../../lib64:/usr/local/cuda-11.3/lib64:/usr/local/cuda-11.3/lib64:
      2023-04-01 11:41:15.651162: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open
       shared object file: No such file or directory; LD_LIBRARY_PATH: /home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/cv2/../../lib64:/usr/local/cuda-11.3/lib64:/usr/local/cuda-11.3/l
      ib64:
      2023-04-01 11:41:15.651178: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure
       the missing libraries mentioned above are installed properly.
      Epoch 0: 100%|▉| 17447/17449 [Basic image is 943742040, loss=0.0165, v_num=2, train/rgb_coarse=0.000147, train/rgb_fine=0.0143, train/transmittance_coarse=8.53e-7, train/transmittance_fine=1.19e-5, train/ps
      nr=
      Basic image is 709385760?it/s]
      Basic image is 709385760
      Basic image is 2099498160
      Basic image is 482285680
      Basic image is 1970097420
      
        Basic image is 1970097420   0%|                                                                                                                                                             | 0/2 [00:01<?,
      ?it/s]
      Basic image is 943742040
      Epoch 1:  27%|▎| 4678/17449 [1:24:10<3:49:48,  1.08s/it, loss=0.016, v_num=2, train/rgb_coarse=0.000172, train/rgb_fine=0.0167, train/transmittance_coarse=7.86e-7, train/transmittance_fine=1.13e-5, train/ps
      nr=
      Epoch 1:  27%|▎| 4679/17449 [1:24:11<3:49:45,  1.08s/it, loss=0.016, v_num=2, train/rgb_coarse=0.000172, train/rgb_fine=0.0167, train/transmittance_coarse=7.86e-7, train/transmittance_fine=1.13e-5, train/ps
      Epoch 1:  27%|▎| 4782/17449 [1:24:33<3:44Epoch 1:  27%|▎| 4796/17449 [1:24:37<3:43:14,  1.06s/it, loss=Epoch 1: 100%|████████████████Basic image is 943742040██████████████████████████████████████▉| 17447/17
      449 [2:12:43<00:00,  2.19it/s, loss=0.0149, v_num=2, train/rgb_coarse=0.000145, train/rgb_fine=0.0141, train/transmittance_coarse=5.28e-7, train/transmittance_fine=1.07e-5, train/psnr=18.50, val/psnr=16.40]
      Basic image is 709385760?it/s]
      Basic image is 482285680
      Basic image is 1970097420
      Basic image is 709385760
      Basic image is 2099498160
      
                                                                                                            Basic image is 1970097420   0%|
                                                                                                                                                                                              | 0/2 [00:01<?, ?it/s]
      Basic image is 943742040
      Epoch 2: 100%|████████████████Basic image is 943742040██████████████████████████████████████▉| 17447/17449 [3:18:57<00:01,  1.46it/s, loss=0.0142, v_num=2, train/rgb_coarse=0.000144, train/rgb_fine=0.0137,
      train/transmittance_coarse=6.48e-7, train/transmittance_fine=1.21e-5, train/psnr=18.60, val/psnr=16.60]
      Basic image is 709385760?it/s]
      
      Basic image is 482285680
      Basic image is 1970097420
      Basic image is 709385760
      Basic image is 2099498160
      Basic image is 1970097420
      Basic image is 943742040
      Epoch 3: 100%|████████████████Basic image is 943742040████████████████████████████████████████▉| 17447/17449 [4:25:45<00:01,  1.09it/s, loss=0.0134, v_num=2, train/rgb_coarse=0.000104, train/rgb_fine=0.010,
       train/transmittance_coarse=5.54e-7, train/transmittance_fine=1.2e-5, train/psnr=20.00, val/psnr=16.40]
      Basic image is 709385760?it/s]
      
      Basic image is 482285680
      Basic image is 1970097420
      Basic image is 709385760
      Basic image is 2099498160
      
                                                                                                            Basic image is 1970097420   0%|
                                                                                                                                                                                              | 0/2 [00:01<?, ?it/s]
      Basic image is 943742040
      Epoch 4: 100%|████████████████Basic image is 943742040███████████████████████████████████████▉| 17447/17449 [5:32:38<00:02,  1.14s/it, loss=0.0129, v_num=2, train/rgb_coarse=0.000125, train/rgb_fine=0.0122,
       train/transmittance_coarse=6.06e-7, train/transmittance_fine=1.3e-5, train/psnr=19.10, val/psnr=16.50]
      Basic image is 709385760?it/s]
      
      Basic image is 482285680
      Basic image is 1970097420
      Basic image is 709385760
      Basic image is 2099498160
      
                                                                                                            Basic image is 1970097420   0%|
                                                                                                                                                                                              | 0/2 [00:01<?, ?it/s]
      Basic image is 943742040
      Epoch 5: 100%|████████████████Basic image is 943742040███████████████████████████████████████▉| 17447/17449 [6:39:37<00:02,  1.37s/it, loss=0.0125, v_num=2, train/rgb_coarse=0.000116, train/rgb_fine=0.0105,
       train/transmittance_coarse=5.1e-7, train/transmittance_fine=1.38e-5, train/psnr=19.80, val/psnr=16.40]
      Basic image is 709385760?it/s]
      
      Basic image is 482285680
      Basic image is 1970097420
      Basic image is 709385760
      Basic image is 2099498160
      Basic image is 943742040
      Epoch 6: 100%|████████████████Basic image is 482285680███████████████████████████████████████▉| 17447/17449 [7:45:29<00:03,  1.60s/it, loss=0.0119, v_num=2, train/rgb_coarse=0.000141, train/rgb_fine=0.0126,
       train/transmittance_coarse=5.3e-7, train/transmittance_fine=1.16e-5, train/psnr=19.00, val/psnr=16.40]
      Basic image is 1970097420it/s]
      
      Basic image is 943742040
      Basic image is 709385760
      Basic image is 709385760
      Basic image is 2099498160
      Basic image is 1970097420
      Basic image is 943742040
      Epoch 7: 100%|████████████████Basic image is 482285680██████████████████████████████████████▉| 17447/17449 [8:51:46<00:03,  1.83s/it, loss=0.0123, v_num=2, train/rgb_coarse=0.000142, train/rgb_fine=0.0121,
      train/transmittance_coarse=5.99e-7, train/transmittance_fine=1.38e-5, train/psnr=19.20, val/psnr=16.20]
      Basic image is 1970097420it/s]
      
      Basic image is 943742040
      Basic image is 709385760
      Basic image is 709385760
      Basic image is 2099498160
      Basic image is 1970097420
      Basic image is 943742040
      Epoch 8: 100%|████████████████Basic image is 943742040███████████████████████████████████████▉| 17447/17449 [9:58:43<00:04,  2.06s/it, loss=0.0114, v_num=2, train/rgb_coarse=0.000119, train/rgb_fine=0.010,
      train/transmittance_coarse=6.11e-7, train/transmittance_fine=1.31e-5, train/psnr=20.00, val/psnr=16.20]
      Basic image is 709385760?it/s]
      
      Basic image is 482285680
      Basic image is 1970097420
      Basic image is 709385760
      Basic image is 2099498160
      Basic image is 1970097420
      Basic image is 943742040
      Epoch 9: 100%|████████████████Basic image is 709385760██████████████████████████████████████▉| 17447/17449 [11:04:26<00:04,  2.29s/it, loss=0.0114, v_num=2, train/rgb_coarse=0.000126, train/rgb_fine=0.011,
      train/transmittance_coarse=5.53e-7, train/transmittance_fine=1.29e-5, train/psnr=19.60, val/psnr=16.10]
      Basic image is 2099498160it/s]
      
      Basic image is 943742040
      Basic image is 709385760
      Basic image is 482285680
      Basic image is 1970097420
      
                                                                                                            Basic image is 1970097420   0%|
                                                                                                                                                                                              | 0/2 [00:01<?, ?it/s]
      Basic image is 943742040
      Epoch 9: 100%|███████████████████████████████████████████████████████████████████████████████| 17449/17449 [11:04:38<00:00,  2.29s/it, loss=0.0114, v_num=2, train/rgb_coarse=0.000126, train/rgb_fine=0.011,
      train/transmittance_coarse=5.53e-7, train/transmittance_fine=1.29e-5, train/psnr=19.60, val/psnr=16.40]
      The best model is saved in /home/guozebin/work_code/LargeScaleNeRFPytorch/data/ckpts/exp/block_0_{epoch:d}/epoch=0-step=17447.ckpt
      
      The best model is saved in /home/guozebin/work_code/LargeScaleNeRFPytorch/data/ckpts/exp/block_0_{epoch:d}/epoch=0-step=17447.ckpt
      The best model is saved in /home/guozebin/work_code/LargeScaleNeRFPytorch/data/ckpts/exp/block_0_{epoch:d}/epoch=0-step=17447.ckpt
      The best model is saved in /home/guozebin/work_code/LargeScaleNeRFPytorch/data/ckpts/exp/block_0_{epoch:d}/epoch=0-step=17447.ckpt

请问这是什么问题？
还有block-index代表什么？需要如何设置呢？我这里使用默认的0
我拿您在谷歌网盘上上传的19gb数据集进行的训练，这个数据集应该是waymo的缩小版，我的理解应该没有问题吧

**Comment by sjtuytc** [comment]
是的，旧版的block nerf已经不在使用了，只供大家复现参考。

**Comment by Bin-ze** [comment]
但是旧版本的代码还在啊，您的意思是旧版本的代码已经无法得到之前的精度了吗？无法达到的原因是什么？这对我很重要！您可以告诉我吗

发自我的iPhone

**Comment by sjtuytc** [comment]
之前的精度就不高呀

**Comment by sjtuytc** [comment]
#79

**Comment by Bin-ze** [comment]
> 之前的精度就不高呀

https://user-images.githubusercontent.com/31123348/200509378-4b9fe63f-4fa4-40b1-83a9-b8950d981a3b.mp4
这里是您展示的结果，从视频效果上来看，psnr至少超过了28，但是这里：
![image](https://user-images.githubusercontent.com/72087870/229390988-12cd6b30-e4c1-4b20-a30d-02fb8a11dac9.png)
从结果上看psnr不会超过18，这相差了10，我应该怎样解决这样的gap呢

**Comment by sjtuytc** [comment]
上面展示的是fouriergrid的结果啊不是blocknerf

**Comment by Bin-ze** [comment]
> 上面展示的是fouriergrid的结果啊不是blocknerf

这是单单训练一个block的结果吧
fouriergrid是不是也可以支持多个block的训练啊

**Comment by sjtuytc** [comment]
可以支持

**Comment by Bin-ze** [comment]
非常感谢！我看了fouriergrid关于waymo数据集的配置，我想知道使用fouriergrid在waymo数据集上训练多个block的nerf时，
    parser.add_argument("--num_per_block", type=int, default=-1,
                        help='Number of images per block. Set to -1 to forbid block training.')

这个配置应该设置为多少，默认为-1，表示禁用块训练

**Comment by sjtuytc** [comment]
你可以尝试一下，理论上越多block效果越好

**Comment by Bin-ze** [comment]
> 你可以尝试一下，理论上越多block效果越好

我发现fouriergrid需要的waymo数据集格式也跟block-nerf不同了，但是README中并没有展示如何将数据进行format，您可以将数据结构目录树发我吗？

**Comment by sjtuytc** [comment]
你可以看一下别的issue，我目前也没有这个目录树了

**Comment by Bin-ze** [comment]
> 你可以看一下别的issue，我目前也没有这个目录树了

我查看了所以issues，应该还没有人用fouriergrid在waymo数据集上训练多个block的nerf，我又仔细看了下fouriergrid中关于waymo数据集读取的代码：
      
      def load_waymo(args, cfg, ):
          data_cfg = cfg.data
          load_img = False if args.program == "gen_trace" else True
          basedir = data_cfg.datadir
          with open(os.path.join(basedir, f'metadata.json'), 'r') as fp:
              metadata = json.load(fp)
          if 'sample_cam' in data_cfg:
              metadata = sample_metadata_by_cam(metadata, data_cfg['sample_cam'])
          if args.sample_num > 0:
              sample_idxs = list(range(0, args.sample_num * data_cfg['sample_interval'], data_cfg['sample_interval']))
              assert args.sample_num * data_cfg['sample_interval'] < len(metadata['train']['file_path']), \
                  f"Not enough data to train with given sample interval: {data_cfg['sample_interval']}!"
          elif 'sample_idxs' in data_cfg:
              sample_idxs = data_cfg['sample_idxs']
          else:
              sample_idxs = None
          
          metadata = sort_metadata_by_pos(metadata)
          metadata = sample_metadata_by_idxs(metadata, sample_idxs)
      
          if "training_ids" in cfg.data:
              training_ids = cfg.data.training_ids
              # if 'assign_pos' in cfg.data:
              #     assign_pos, assign_rot = cfg.data.assign_pos, cfg.data.assign_rot
              # else:
              #     assign_pos, assign_rot = None, None
              # if args.program == 'tune_pose':
              #     rand_vec = np.random.rand(3)
              #     lw, up = np.array(cfg.data.search_rot_lower), np.array(cfg.data.search_rot_upper)
              #     cur_rot = lw + (up - lw) * rand_vec
              #     rand_vec = np.random.rand(3)
              #     lw, up = np.array(cfg.data.search_pos_lower), np.array(cfg.data.search_pos_upper)
              #     cur_pos = lw + (up - lw) * rand_vec
              #     assign_pos[cfg.data.tunning_id] = cur_pos.tolist()
              #     assign_rot[cfg.data.tunning_id] = cur_rot.tolist()
              #     args.running_rot = np.round(cur_pos, 4).tolist() + np.round(cur_rot, 2).tolist()
              metadata = sample_metadata_by_training_ids(metadata, training_ids, None, None)
          rotations = find_rotations_from_meta(metadata)
          if args.diffuse:
              for idx, fp in enumerate(metadata['train']['file_path']):
                  img_name = fp.split("/")[-1].replace(".png", "")
                  diffuse_replace = cfg.diffusion.diff_replace
                  if img_name in diffuse_replace:
                      img_path = os.path.join(cfg.diffusion.diff_root, diffuse_replace[img_name] + ".png")
                      metadata['train']['file_path'][idx] = img_path
          
          # The validation datasets are from the official val split, 
          # but the testing splits are hard-coded sequences (completely novel views)
          tr_cam_idx, val_cam_idx = metadata['train']['cam_idx'], metadata['val']['cam_idx']
          cam_idxs = tr_cam_idx + val_cam_idx
          train_pos, val_pos = metadata['train']['position'], metadata['val']['position']
          positions = train_pos + val_pos
          tr_im_path, val_im_path = metadata['train']['file_path'], metadata['val']['file_path']
          tr_c2w, val_c2w = metadata['train']['cam2world'], metadata['val']['cam2world']
          tr_K, val_K = metadata['train']['K'], metadata['val']['K']
      
          # Determine split id list
          i_split = [[], [], []]
          loop_id = 0
          for _ in tr_c2w:
              i_split[0].append(loop_id)
              loop_id += 1
          for _ in val_c2w:
              i_split[1].append(loop_id)
              loop_id += 1
      
          # Load camera poses
          poses = []
          for c2w in tr_c2w:
              poses.append(np.array(c2w).reshape(4,4))
          for c2w in val_c2w:
              poses.append(np.array(c2w).reshape(4,4))
      
          # Load images
          if not load_img:
              imgs = tr_im_path + val_im_path  # do not load all the images
          else:
              imgs = []
              print(f"Loading all the images to disk.")
              for path in tqdm(tr_im_path):
                  imgs.append(imageio.imread(os.path.join(basedir, path)) / 255.)
              for path in tqdm(val_im_path):
                  imgs.append(imageio.imread(os.path.join(basedir, path)) / 255.) 
          
          train_HW = np.array([[metadata['train']['height'][i], metadata['train']['width'][i]] 
                               for i in range(len(metadata['train']['height']))]).tolist()
          val_HW = np.array([[metadata['val']['height'][i], metadata['val']['width'][i]] 
                             for i in range(len(metadata['val']['height']))]).tolist()
      
          if args.save_train_imgs:
              save_training_imgs_to_disk(args, cfg, metadata)
          train_HW, val_HW, imgs, tr_K, val_K = resize_img(train_HW, val_HW, imgs, tr_K, val_K)
      
          # Create the test split
          te_c2w, test_HW, test_K, test_cam_idxs, test_pos = \
              gen_rotational_trajs(args, cfg, metadata, tr_c2w, train_HW, tr_K, tr_cam_idx, train_pos, 
                             rotate_angle=data_cfg.test_rotate_angle)
          # te_c2w, test_HW, test_K, test_cam_idxs = \
          #     gen_straight_trajs(metadata, tr_c2w, train_HW, tr_K, tr_cam_idx, train_pos, 
          #                    rotate_angle=data_cfg.test_rotate_angle)
          # dummy test paths
          # te_c2w, test_K, test_HW, test_cam_idxs = val_c2w, val_K, val_HW, val_cam_idx
          # TODO: consider removing the so-called test split.
          for _ in te_c2w:
              i_split[2].append(loop_id)
              loop_id += 1
          for c2w in te_c2w:
              poses.append(np.array(c2w).reshape(4,4))
          
          # Bundle all the data
          all_K = np.array(tr_K + val_K + test_K)
          HW = np.array(train_HW + val_HW + test_HW)
          poses = np.stack(poses, 0)
          if load_img:
              imgs = np.stack(imgs)
              
          # note test_cam_idxs can be inaccurate because it may be varied!
          cam_idxs += test_cam_idxs
          render_poses = te_c2w
          return imgs, poses, render_poses, HW, all_K, cam_idxs, i_split

由于需要知道metadata.json，但是此处的metadata.json与block-nerf中读取数据代码中的：
   self.meta = torch.load(os.path.join(self.root_dir, f'train/train_all_meta.pt'))

数据结构是不相同的，因此我很难继续开展工作，所以我想问下您可以告诉我在当初进行实验时，该数据时如何处理的吗，我不需要处理代码，我只需要知道其数据结构跟每个部分的含义，我将自己对waymo数据集进行format，以支持fouriergrid的多block训练

**Comment by sjtuytc** [comment]
别的Issue里有

**Comment by Bin-ze** [comment]
找到了，感谢🙏

**Comment by Bin-ze** [comment]
> 别的Issue里有

我尝试使用waymo_block.py配置进行训练，观察数据处理后发现，在进行处理时会一次性将一个block的900数据读入GPU然后送入渲染器，这样需要极大的显存，请问您有没有出现OOM问题？该如何解决？


def load_waymo_data(args, cfg):
    data_cfg = cfg.data
    K, depths = None, None
    near_clip = None
    images, poses, render_poses, HW, K, cam_idxs, i_split = load_waymo(args, cfg)
    print(f"Loaded waymo dataset.")
    i_train, i_val, i_test = i_split
    near_clip, far = inward_nearfar_heuristic(poses[i_train, :3, 3], ratio=0.02)  # not used too much in fact
    
    # load near and far parameters
    if "near_clip" in data_cfg:
        near_clip = data_cfg['near_clip']
    if 'near' in data_cfg:
        near = data_cfg['near']
    if 'far' in data_cfg:
        far = data_cfg['far']
    Ks = np.array(K)
    irregular_shape = False
    data_dict = dict(
        HW=HW, Ks=Ks, near=near, far=far, near_clip=near_clip,
        i_train=i_train, i_val=i_val, i_test=i_test,
        poses=poses, render_poses=render_poses, images=images, depths=depths, cam_idxs=cam_idxs, irregular_shape=irregular_shape
    )
    data_dict['poses'] = torch.tensor(data_dict['poses']).float()
    data_dict['images'] = torch.tensor(data_dict['images']).float() # 在这里由于一个block的图像数量过多，占用显存超过28GB报错
    return data_dict
