### ISSUE TITLE
报错： self.density.grid[nearest_dist[None, None] <= near_clip] = -100 IndexError: The shape of the mask [1, 1, 50, 50, 50] at index 1 does not match the shape of the indexed tensor [1, 7, 50, 50, 50] at index 1

### ISSUE THREAD

**Issue by Bin-ze** [dvlab-research/BlockNeRFPytorch#102]
非常抱歉，因为一直问您问题，可能给你造成了很大的不便。
我运行'FourierGrid/configs/waymo/waymo_block.py'配置，以期望训练分块nerf。
但是出现以下问题：
      
      Traceback (most recent call last):
        File "/home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
          return func(*args, **kwargs)
        File "/home/guozebin/work_code/LargeScaleNeRFPytorch/FourierGrid/FourierGrid_model.py", line 403, in maskout_near_cam_vox
          self.density.grid[nearest_dist[None, None] <= near_clip] = -100
      IndexError: The shape of the mask [1, 1, 50, 50, 50] at index 1 does not match the shape of the indexed tensor [1, 7, 50, 50, 50] at index 1
      
      Process finished with exit code 1

问题定位：

        # maskout grid points that between cameras and their near planes
        self_grid_xyz = torch.stack(torch.meshgrid(
            torch.linspace(self.xyz_min[0], self.xyz_max[0], self.world_size_density[0]),
            torch.linspace(self.xyz_min[1], self.xyz_max[1], self.world_size_density[1]),
            torch.linspace(self.xyz_min[2], self.xyz_max[2], self.world_size_density[2]),
        ), -1)
        nearest_dist = torch.stack([(self_grid_xyz.unsqueeze(-2) - co).pow(2).sum(-1).sqrt().amin(-1) for co in cam_o.split(10)]).amin(0)
        self.density.grid[nearest_dist[None, None] <= near_clip] = -100 

nearest_dist[None, None] <= near_clip索引的维度 [1, 1, 50, 50, 50] 与 self.density.grid 的维度[1, 7, 50, 50, 50]不匹配，请问这可能是什么问题导致的呢？

**Comment by sjtuytc** [comment]
这个我没有遇到过哎

**Comment by Bin-ze** [comment]
不好意思，我再问您一个问题，您在这里：
https://github.com/sjtuytc/UnboundedNeRFPytorch/issues/101#:~:text=6%20hours%20ago-,%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81,-Author
提到FourierGrid可以支持多个block的训练，但是在run_FourierGrid.py中，args.running_block_id设置为-1，且在读取waymo数据集时，也只是读取了一个block的数据用于训练，因此我没有理解您提到的”可以支持多个block的训练“这句话的含义，你可以解释一下吗？感谢！

**Comment by Bin-ze** [comment]
> 这个我没有遇到过哎

这个应该是您的仓库的bug，当设置maskout_lt_nviews>0，就会出现，您可以测试一下

**Comment by sjtuytc** [comment]
maskout_lt_nviews是历史遗留的选项，我们并没有用这个
