### ISSUE TITLE
May I ask how to solve this video rendering problem

### ISSUE THREAD

**Issue by cnu-Dawn** [dvlab-research/BlockNeRFPytorch#103]
请问我按照给出的步骤进行操作，生成的渲染视频与预期差别很大，是什么原因呢？
1、我先运行了[get_one_block_meta_and_visualize.py]生成metadata.json,并安置在目录下
2、运行python run_FourierGrid.py --program train --config FourierGrid/configs/waymo/waymo_no_block.py --num_per_block 100 --render_video --exp_id 30
并得出渲染视频。
可是我得出的视频色彩和光照都是扭曲的。请问这是什么原因

https://user-images.githubusercontent.com/109675201/230562919-371f3fe4-4f54-4327-aff6-205afe5b9689.mp4

![3351E064B2F434F757327C7D0C0DF378](https://user-images.githubusercontent.com/109675201/230562951-59ce915b-b049-42c2-beca-4492624ef09d.jpg)

**Comment by sjtuytc** [comment]
感谢关注，Block太大了就会这样，waymo在同一个block里面pose对不上，所以就会扭曲。可能还有cover不全的问题。就是你可以看到我们的方法在m360上挺好的，因为他拍的非常全，但是在waymo里面不同相机的拍照没法很好的对准，你可以跑colmap试试，这跟colmap有关系，sift点找不准。不过我们这个工作只是claim fouriergrid在相同条件下比dvgo的baseline好，在这种情况下两个方法都很难准确。

**Comment by cnu-Dawn** [comment]
是不是要改一下 --num_per_block 100 这个参数

**Comment by sjtuytc** [comment]
是

**Comment by cnu-Dawn** [comment]
请问用A40训练 改到多少较为合适呢？

**Comment by sjtuytc** [comment]
效果来看越小越好但是泛化性能会有影响

**Comment by cnu-Dawn** [comment]
你好 请问我已经对 num_per_block 做了改动 可是情况并没有好转 是不是因为以下报错
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (1096, 1217) to (1104, 1232) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).

**Comment by sjtuytc** [comment]
这个warning应该无所谓

**Comment by cnu-Dawn** [comment]
那请问这种扭曲还有解决的办法吗？

**Comment by sjtuytc** [comment]
对于你的问题我给不出更好的方案，一个解决思路是在pose没问题的数据集上尝试我们的方法

**Comment by cnu-Dawn** [comment]
感谢
