### ISSUE TITLE
关于mega-nerf数据集在FourierGrid运行的问题

### ISSUE THREAD

**Issue by buer1121** [dvlab-research/BlockNeRFPytorch#104]
你好，想请教下数据集一些文件的生成问题
mega-nerf数据集（building为例是下述结构：）
![image](https://user-images.githubusercontent.com/48516434/231084579-9a68f318-2bfa-4316-a986-eb6bfc56f86d.png)

但是在FourierGrid下是需要metadata.json文件，这个文件的生成方式好像没有看到，只看到了waymo数据集从下载到生成这些json文件的方式（下图），好像是没办法直接应用到mega-nerf到数据集上面，想问下这个您是怎么处理到？
![image](https://user-images.githubusercontent.com/48516434/231086012-03d0e805-b096-41bc-802b-e2e5c3446ae1.png)

期待你的回复！

**Comment by sjtuytc** [comment]
Mega NeRF不再支持了，感觉数据集差别非常大，而且需要很多额外的tricks.

**Comment by buer1121** [comment]
> Mega NeRF不再支持了，感觉数据集差别非常大，而且需要很多额外的tricks.

那如果是自己采集的数据集（非小场景），
