### ISSUE TITLE
waymo数据集

### ISSUE THREAD

**Issue by cnu-Dawn** [dvlab-research/BlockNeRFPytorch#105]
你好，我想问一下根据waymo数据集下生成的metadata.json都包含图片的哪些信息，大量.pt文件是什么用途，以及split_block_train.json，train_all_meta.json，cam_info.json这几个文件的作用都是什么？

**Comment by sjtuytc** [comment]
具体的我忘了，你只要在代码库里搜索这几个文件，就能看到每个文件包括哪些dict和 keys。都是些常见的变量。

**Comment by cnu-Dawn** [comment]
那请问.pt后缀的文件代表什么意思呢

**Comment by sjtuytc** [comment]
模型文件吧我记得或者是pytorch的dict
