### ISSUE TITLE
用自己的数据集跑360

### ISSUE THREAD

**Issue by cnu-Dawn** [dvlab-research/BlockNeRFPytorch#107]
请问用自己的数据集运行360，如何生成pause文件夹中的那几个文件？

**Comment by sjtuytc** [comment]
哪里有pause文件夹

**Comment by cnu-Dawn** [comment]
就是poses_bounds.npy，cameras.bin，images.bin，points3D.bin 这四个文件。

**Comment by sjtuytc** [comment]
可以参考之前的仓库，比如DVGO，llff，等等，或者直接在github搜索。

**Comment by cnu-Dawn** [comment]
mip-360能否对一个室内环境进行重建，还是说只能对小物件重建？

**Comment by sjtuytc** [comment]
Demo不是显示了很多室内场景么

**Comment by cnu-Dawn** [comment]
请问我运行colmap后，下采样images_4和image_8并没有出现照片是为什么？

**Comment by sjtuytc** [comment]
有个开关可以开下采样，请参考colmap或者别的仓库的issue

**Comment by cnu-Dawn** [comment]
请问不对图片进行下采样，可以跑mip-360吗

**Comment by sjtuytc** [comment]
可以呀只要换个路径就行了

**Comment by cnu-Dawn** [comment]
请问这个magick是指什么呀？
Factors: [2, 4, 8]
Minifying 2 data/garden/dense
magick mogrify -resize 50% -format png *.JPG
sh: 1: magick: not found
Removed duplicates

**Comment by sjtuytc** [comment]
一个图片处理工具，谷歌一下

**Comment by sjtuytc** [comment]
Closed because of no further response.
