### ISSUE TITLE
How to use  San Fran Cisco Mission Bay

### ISSUE THREAD

**Issue by Jitaseal** [dvlab-research/BlockNeRFPytorch#111]
我下载了**经过预处理的waymo数据**，解压之后组织形式如下：
data
   |——————pytorch_waymo_dataset                     // the root folder for San Fran Cisco Mission Bay
   |        └——————cam_info.json                    // extracted cam2img information in dict.
   |        └——————coordinates.pt                   // global camera information used in Mega-NeRF, deprecated
   |        └——————train                            // train data
   |        |         └——————metadata               // meta data per image (camera information, etc)
   |        |         └——————rgbs                   // rgb images
   |        |         └——————split_block_train.json // split block informations
   |        |         └——————train_all_meta.json    // all meta informations in train folder
   |        └——————val                              // val data with the same structure as train

在配置了数据集路径之后，运行了：
`python run_FourierGrid.py --program train --config FourierGrid/configs/waymo/waymo_no_block.py --num_per_block 100 --render_video --exp_id 30`

但是我发现找不到metadata.json，在查看了数据集之后，的确没有发现这样的文件。出错的位置位于load_waymo.py:
`with open(os.path.join(basedir, f'metadata.json'), 'r') as fp:`

请问我应该怎样配置我的路径或者重新组织我的数据呢？

**Comment by sjtuytc** [comment]
#105 
#72 
#53

**Comment by sjtuytc** [comment]
就是简单的把train val合起来，代码里也有

**Comment by sjtuytc** [comment]
https://github.com/sjtuytc/UnboundedNeRFPytorch/blob/53d009843ecd40d1ec35446480ba8fcceba3df92/data_preprocess/comvog_organize_by_cam_pos.py

**Comment by Jitaseal** [comment]
> https://github.com/sjtuytc/UnboundedNeRFPytorch/blob/53d009843ecd40d1ec35446480ba8fcceba3df92/data_preprocess/comvog_organize_by_cam_pos.py
非常感谢

**Comment by KnightOfTheMoonlight** [comment]
@sjtuytc  Hi thanks sharing this great work.        Could you share the waymo block nerf data manual homepage for use to get a clear understanding of their data?

**Comment by sjtuytc** [comment]
> @sjtuytc Hi thanks sharing this great work. Could you share the waymo block nerf data manual homepage for use to get a clear understanding of their data?

Thanks for your appreciation and attention. I think the code is self-explained because the data is just a dictionary with very common key names. You only need to remember that metadata is a combination of train_meta and val_meta. I will update this repo shortly after I finish a recent submission.

**Comment by KnightOfTheMoonlight** [comment]
> > @sjtuytc Hi thanks sharing this great work. Could you share the waymo block nerf data manual homepage for use to get a clear understanding of their data?
> 
> Thanks for your appreciation and attention. I think the code is self-explained because the data is just a dictionary with very common key names. You only need to remember that metadata is a combination of train_meta and val_meta. I will update this repo shortly after I finish a recent submission.

As you mentioned in other issues 
[issue91]( https://github.com/sjtuytc/UnboundedNeRFPytorch/issues/91#issuecomment-1478803904), there is some wrong with the camera poses, an official manual might clear this confusion.

Thanks for keep updating this repo.

**Comment by sjtuytc** [comment]
I have to say that this issue might not easily be addressed by ours. I'll probably say a few words on it later.
