### ISSUE TITLE
block-nerf

### ISSUE THREAD

**Issue by Korace0v0** [dvlab-research/BlockNeRFPytorch#112]
您好， 我尝试用您给出的block-nerf权重进行可视化，但是得到的结果并不太理想，请问您知道哪里会出现问题吗？
https://github.com/sjtuytc/UnboundedNeRFPytorch/issues/36#issuecomment-1246353338

训练日志文件如下：
![image](https://user-images.githubusercontent.com/39874544/235344850-beab8305-54a2-4b1c-8c3d-6b5c7701b4c0.png)

附带我自己训练的结果，
![image](https://user-images.githubusercontent.com/39874544/235344821-8fe003b6-f2f8-4e6c-8e72-833b915b91f0.png)
以及根据您给出的权重，进行可视化得到的rbg和depth结果
![image](https://user-images.githubusercontent.com/39874544/235344913-97294d79-837d-46d0-bc6a-e7c877389737.png)

请问现在的结果是否是正常的情况呢？
感谢您的帮助

**Comment by sjtuytc** [comment]
正常

**Comment by Korace0v0** [comment]
根据您给出的权重文件可视化结果应该不太正常吧 😂，block nerf的代码是否经过修改了呢？

我主要希望了解的是block nerf是否能够渲染出一个比较良好的深度图，但目前可视化结果中的深度渲染效果都很不理想，在您之前的实验里，深度图的可视化效果怎么样呢？

感谢您的帮助

**Comment by sjtuytc** [comment]
正常

**Comment by sjtuytc** [comment]
不用谢，感谢你的关注，祝顺利
