### ISSUE TITLE
about load_waymo_data

### ISSUE THREAD

**Issue by JinchengLiang** [dvlab-research/BlockNeRFPytorch#116]
I am confused about loading the Waymo data. In the ```def load_waymo``` in load_waymo.py, it loads the ```metadata.json``` by 
```with open(os.path.join(basedir, f'metadata.json'), 'r') as fp:```. But there is no ```metadata.json``` in the Waymo data that you provide, is it means ```train_all_meta.json```? 
However, further in the code, there is ```list_idxs = list(range(len(metadata[split]['position'])))``` in ```def sort_metadata_by_pos```. But there is no key named 'position' in the ```train_all_meta.json```. Did I miss some procedure that process the dataset?

**Comment by sjtuytc** [comment]
Please refer to previous issues.

**Comment by JinchengLiang** [comment]
Thank you, I got it. #111

**Comment by JinchengLiang** [comment]
```if len(cur_meta['c2w']) < 4: cur_meta['c2w'].append([0.0, 0.0, 0.0, 1.0])``` json文件里没有'c2w'，只有'transform_matrix'，这里是要把c2w改成transform_matrix吗，还是transform_matrix改成c2w?

**Comment by sjtuytc** [comment]
这两个我记得没差别，你可以搜索一下代码

**Comment by JinchengLiang** [comment]
代码里面两个都有，我两个都保留吧，然后做成4x4

**Comment by JinchengLiang** [comment]
你好，我训练原始的block-nerf，往往随着train/loss的下降和train/psnr的上升，val/loss却上升，val/psnr却下降，也就是train的效果越来越好，val的效果却越来越差。请问你们有遇到这种情况吗？
这是我运行的命令：`python ./UnboundedNeRFPytorch/train_block_nerf.py --block_index 2 --num_epochs 10 --decay_step 7 --exp block2 --refresh_every 1000 --num_gpus 1`
这是几个block的结果：
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/121146314/f8576a00-9d91-41b8-aff8-e70b639aab00)
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/121146314/7372081c-120a-4a68-91ae-eaad9d9e8f07)

**Comment by sjtuytc** [comment]
Blocknerf已经不再被我们支持
