### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './logs/tanks_and_temple_unbounded'

### ISSUE THREAD

**Issue by jdiazram** [dvlab-research/BlockNeRFPytorch#117]
Hi, nice work.
When I run:
 `python run_FourierGrid.py --program train --config FourierGrid/configs/tankstemple_unbounded/playground_single.py --num_per_block -1 --render_train --render_test --render_video --exp_id 57` 

I get this error:

`FileNotFoundError: [Errno 2] No such file or directory: './logs/tanks_and_temple_unbounded'`

What am I missing?

Thx

**Comment by sjtuytc** [comment]
mkdir logs

This command is in the installation guide.

**Comment by jdiazram** [comment]
Thx, but I don't find the command in the installation guide. I created a directory "logs" in the FourierGrid folder because in the root there is one folder called logs (attach an image), and nothing happens, and I get the same error. Can you help me?

![Screenshot from 2023-05-28 10-32-08](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/45439493/16ace370-3300-4450-83a4-95c1ee768196)

**Comment by sjtuytc** [comment]
Logs is just an empty folder to store all training logs and ckpts and rendering results.

**Comment by jdiazram** [comment]
Yes, but in which location must be this ./logs/tanks_and_temple_unbounded folder?
Thx

**Comment by sjtuytc** [comment]
Quick fix: Just create it at where it goes wrong.

**Comment by sjtuytc** [comment]
I checked the doc, this instruction is already in the commit list but not in the remote repo now.

**Comment by jdiazram** [comment]
I changed the "logs" symbolic link to "logs_0" and created the logs/tanks_and_temple_unbounded directory, and now it's training. I hope this change doesn't hurt regular training.
Thx
