### ISSUE TITLE
Questions about near and far plane in block nerf

### ISSUE THREAD

**Issue by Madaoer** [dvlab-research/BlockNeRFPytorch#12]
Thanks for great work! I once used waymo open dataset for blocknerf to reconstruct city scene. However it shows that there is no near and far plane information in its dataset, which seems necessary in  training nerf model. I wonder how to deal with it.

**Comment by ghost** [comment]
The author of the email says that near and far are 1 and 1000 respectively, but considering that the dataset is scaled, I think you can try with 0.01 and 10

**Comment by Madaoer** [comment]
Tks!

**Comment by MiZhenxing** [comment]
Hi, sorry to disturb. I would like to ask If I directly use the original ray directions and origins in the waymo dataset, are the near and far are still 0.01 and 10, or I need to use 1 and 1000. Thank you very much!

**Comment by sjtuytc** [comment]
I don't think the official paper presents the near and far parameters. 
So I think 0.01 and 15 is a good initial try.
I don't think we have changed the rd and ros. They should be the same as this repo.

**Comment by MiZhenxing** [comment]
Got it! Thanks for your quick response!
