### ISSUE TITLE
Bugs in Block-NeRF

### ISSUE THREAD

**Issue by JinchengLiang** [dvlab-research/BlockNeRFPytorch#120]
block-nerf的实现有几处错误，主要集中在mip-nerf的部分。
1. 最严重的是 `mean_t` in `get_cone_mean_conv`，`mean_t`直接写成了和`variance_t`一样的表达式： 
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/121146314/d87b05bf-1c55-4d2a-b3e3-af4e6fb41a93)
直接导致结果非常糟糕

2. `noise` in `volume_rendering`：
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/121146314/87fc7ef4-acbf-4337-a159-81337e651667)
这里的noise范围是[0,1)，太大了，要知道sigmas的范围也是[0,1)

3. `weights` in `sample_pdf`： 
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/121146314/4be7bb20-8fa6-418a-9906-0a5a2e3b57f6)
根据原文，这里应该是 `weights = weights_blur + alpha`

上述错误都在/block_nerf/rendering.py

**Comment by sjtuytc** [comment]
感谢你的关注和支持，BlockNeRF已经不再被我们支持，与我们的研究暂无关系。
不过如果你改动可以达到更好的效果，欢迎PR，我代表社区对你表示非常感谢。

**Comment by JinchengLiang** [comment]
好的，我还没有training太多，现在的结果是10个epochs后psnr=21还可以上升。
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/121146314/2fec792d-88ab-4387-872f-f57e2a823bdd)

**Comment by sjtuytc** [comment]
这个曲线不关键，要看渲染的结果

**Comment by OkuChou** [comment]
> 2\. noise
请问这里的noise该怎么设置呀？
