### ISSUE TITLE
训练自己数据的相关内容

### ISSUE THREAD

**Issue by HoveXb** [dvlab-research/BlockNeRFPytorch#121]
你好，
1.请问训练自己数据那里，imgs2poses.py文件是在哪里；
2.如果使用其他方式获取到图像的位姿，其位姿的保存格式应该是什么样的呢；
3.使用本仓库渲染出的结果能否导出成点云形式？
非常感谢！

**Comment by sjtuytc** [comment]
1.这个得自己整，我没用过这个，我一般就是colmap
2.colmap格式
3.我不会

**Comment by HoveXb** [comment]
额，仓库所说“Run COLMAP to reconstruct scenes. This would probably cost a long time.”
`python tools/imgs2poses.py data/Madoka`
这个imgs2poses.py能否提供呢

**Comment by sjtuytc** [comment]
我看了还在仓库里啊，在下一个大版本更新里custom这部分会重写，现在这块基本是废废的，并不支持

**Comment by sjtuytc** [comment]
不支持的原因是之前的文档写了基本也没用，现在有更好更新的重建pipeline了，原来的就没在沿用了

**Comment by HoveXb** [comment]
> 我看了还在仓库里啊，在下一个大版本更新里custom这部分会重写，现在这块基本是废废的，并不支持

仓库里都没有tools这个文件夹吧

**Comment by sjtuytc** [comment]
搜索一下，大哥

**Comment by HoveXb** [comment]
找到了。。。额，上文的意思是目前的版本不支持自己训练集的重建吗？

**Comment by sjtuytc** [comment]
目前需要你自己尝试，可以翻之前的issue，有些同学已经在自己数据集上获得了很好的效果

**Comment by HoveXb** [comment]
好的，非常感谢耐心及时的回复，祝科研顺利

**Comment by sjtuytc** [comment]
多谢关注，thanks
