### ISSUE TITLE
显存问题

### ISSUE THREAD

**Issue by StarsTesla** [dvlab-research/BlockNeRFPytorch#124]
我根据README安装了环境和准备了Tanks的那个数据集，然后我发现我直接根据README运行火车那个场景，在单个3090上，随着训练进行，逐渐显存从几个G占到20G直到OOM，同时训练速度也从40it/s逐渐随着显存增加慢慢下降。

起初我觉得可能是显存不够，于是我把代码迁移到服务器上，用A100训练，但是我发现依然存在逐渐显存增加，训练速度下降的问题，训练到8000个step已经占到了35G的显存，我想知道有什么优化的方法吗，是逐渐训练导致grid慢慢增长导致的吗，如果你们在3090ti上训练的话，这个设置应该在3090上能行的通啊，此外，是否能部署到多卡上来减轻单卡的负重呢，多谢！

**Comment by sjtuytc** [comment]
可以减小num_voxels来减轻显存压力，这里的机制是因为有scale schedule. 多卡训练是比较麻烦的一件事，如果grid很大放不下的话怎么分到不同的卡上再汇总梯度呢？可以做但是有点麻烦。

**Comment by StarsTesla** [comment]
那blocknerf也是单卡么

**Comment by sjtuytc** [comment]
你可以不同卡跑不同block

**Comment by StarsTesla** [comment]
然后额外训练不同block之间的视图过渡么？

**Comment by sjtuytc** [comment]
没试过
