### ISSUE TITLE
No module named 'adam_upd_cuda'

### ISSUE THREAD

**Issue by CUGXiaoBao** [dvlab-research/BlockNeRFPytorch#128]
请问这是什么原因呢？

**Comment by sjtuytc** [comment]
没安装好，重新看安装指令

**Comment by CUGXiaoBao** [comment]
可以指一下大概哪有问题吗？ 感觉每一步都过了啊

**Comment by sjtuytc** [comment]
Build extensions

**Comment by CUGXiaoBao** [comment]
No CUDA runtime is found, using CUDA_HOME='/home/xiaobao/miniconda3/envs/large-scale-nerf'
running install
/home/xiaobao/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/xiaobao/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating adam_upd_cuda.egg-info
error: could not create 'adam_upd_cuda.egg-info': Permission denied

在安装基于网格步骤中 运行python setup.py install报此错误   cuda版本为12.2  前边每一步都按照流程走了  请问大佬这个问题该如何解决？

**Comment by sjtuytc** [comment]
好像是权限问题
