### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zcdliuwei** [dvlab-research/BlockNeRFPytorch#129]
您好，我是第一次接触NERF，问一个小白问题，我可以只使用一张自己的图片，场景或者只包含单个目标，然后使用您的代码和预训练模型，渲染出360度视频吗？还是需要先把自己的场景图，手动在不同角度拍几张，再去训练、推理？
期待您的回答

**Comment by sjtuytc** [comment]
这个本仓库解决不了，你可以去群里问

**Comment by zcdliuwei** [comment]
> 这个本仓库解决不了，你可以去群里问

哪里的群？可以告诉我地址吗 谢了

**Comment by CUGXiaoBao** [comment]
同求交流群，谢谢
