### ISSUE TITLE
训练进程自动退出

### ISSUE THREAD

**Issue by CHCDST-SY** [dvlab-research/BlockNeRFPytorch#131]
![a776bc67c7f0a6af233d0bfbabf9277](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/46321100/e5d99976-10f0-4c55-b21b-d38f9d7f80b3)

我使用这行命令进行训练：
python run_FourierGrid.py --program train --config FourierGrid/configs/tankstemple_unbounded/train_single.py --num_per_block -1 --render_train --render_test --render_video --exp_id 12
然而在几十个小时的训练之后，进程退出了。
在logs文件夹中发现了以下数据：
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/46321100/15325a22-1f8d-475c-ac11-e22cdacb5d2e)
但是并未发现渲染好的视频文件，请问是否是我流程没有跑完，接下来该如何做？

**Comment by sjtuytc** [comment]
这个我没遇到过，没有报错信息我也没法判断哪里错了，你只能逐行调试看哪里报错了。注意你不需要重新训练，只要调用相同的命令就可以加载训练好的模型。

**Comment by CHCDST-SY** [comment]
意思是我可以再次运行
python run_FourierGrid.py --program train --config FourierGrid/configs/tankstemple_unbounded/train_single.py --num_per_block -1 --render_train --render_test --render_video --exp_id 12
这行代码，他会自动加载已经训练好的模型，然后再次尝试渲染？

**Comment by sjtuytc** [comment]
是

**Comment by CHCDST-SY** [comment]
![image](https://github.com/sjtuytc/UnboundedNeRFPytorch/assets/46321100/5783c016-7f32-4cb5-b2be-865fdd8f573e)
再次运行程序，显示这个错误。

**Comment by sjtuytc** [comment]
没遇到过，搜索一下吧，估计跟中文路径或者存储系统之类有关系

**Comment by CHCDST-SY** [comment]
好吧。打扰啦。
