### ISSUE TITLE
请教一下运行自己数据的问题

### ISSUE THREAD

**Issue by zekeingithub** [dvlab-research/BlockNeRFPytorch#133]
非常感谢您出色的工作！
现在我想运行自己的数据，但是我看到Build your custom unbounded NeRF有一个(deprecated)的提示，意思是现在不可以运行自己数据的意思吗？感谢您的回复

**Comment by sjtuytc** [comment]
是的，下一个版本中我们会换一个更general的方式，能直接读取colmap结果进行渲染

**Comment by zekeingithub** [comment]
非常感谢您的快速答复。我在浏览了各个Issues中看到了一些成功运行自己数据的情况。我现在有从COLMAP中获得的稀疏点云模型以及相机内外参：cameras.txt，images.txt和points3D.txt. 数据集场景是类似Kitty数据集：利用车辆前置摄像头路拍的场景。我有以下两个问题：
1. 如何进行COLMAP数据预处理，因为我在尝试训练的时候，根据配置文件不同，发现缺失poses_bounds.npy或者metadata.json文件。我不知道该如何生成这些文件，这似乎跟配置文件内部数据有关？
2. 如何选择适合我的路拍场景的配置文件以及参数呢？
非常感谢您的回复！

**Comment by pomoron** [comment]
The poses_bounds.npy files are created through ./FourierGrid/tools/colmap_utils/pose_utils.py. The gen_poses() function runs Colmap, loads the poses and pts3d data and saves the poses as poses_bounds.npy. The line that runs Colmap has a comment that recommends users to comment out the line if they wish to prepare the Colmap poses separately elsewhere.
`run_colmap(basedir, match_type)  # comment this line if you have run the colmap software offline`

For the time being, without more updated utilities, you may wish to call this gen_poses() function yourself. You might also need to massage the load_colmap_data() function a bit to read the cameras.bin/images.bin/points3D.bin in your designated locations.
