### ISSUE TITLE
Export to point clouds

### ISSUE THREAD

**Issue by pomoron** [dvlab-research/BlockNeRFPytorch#137]
Hi Zelin,

Thanks for your great work here to provide us with the utilities to use unbounded NeRF. I would just like to ask about the exporting/rendering functions. I am aware that the main run file run_FourierGrid.py allows rendering the resulting NeRF field into mp4 videos (via ./FourierGrid/run_render.py) or camera/bbox parameters. Would there be any chance to export the resulting visualisation into a point cloud for further processing?

Regards,
Pomoron

**Comment by sjtuytc** [comment]
Thanks for your attention. There is no trivial way to do this. Sorry.
