### ISSUE TITLE
RuntimeError: configuration file type

### ISSUE THREAD

**Issue by mah-asd** [dvlab-research/BlockNeRFPytorch#138]
I'm getting the following error when I run this command: _python run_FourierGrid.py --program train --config FourierGrid/configs/tankstemple_unbounded/playground_single.py --num_per_block -1 --render_train --render_test --render_video --exp_id 57_

"
RuntimeError: The configuration file type in the inheritance chain must match the current configuration file type, either "lazy_import" or non-"lazy_import". You got this error since you use the syntax like `with read_base(): ...` or import non-builtin module in ./UnboundedNeRFPytorch-main/FourierGrid/configs/tankstemple_unbounded/../default.py. See more information in https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html
"

**Comment by sjtuytc** [comment]
I have not seen this issue. Is this because you modified the config file? The source code is here: https://github.com/open-mmlab/mmengine/blob/main/mmengine/config/config.py

**Comment by mah-asd** [comment]
Thank you for your response, I didn't change the config file, I'm simply running: python run_FourierGrid.py --program train --config FourierGrid//configs/waymo/waymo_block.py --num_per_block -1 --render_train --render_test --render_video --exp_id 57 

Still get the same error, the error is for this line: cfg = mmengine.Config.fromfile(args.config)
