### ISSUE TITLE
Question about moving object

### ISSUE THREAD

**Issue by tersite1** [dvlab-research/BlockNeRFPytorch#142]
Hi, 
I understand that Block-NeRF cannot working on large scale city data so the writers erase them by sementic segmentation. 
But how did they fill out the empty area? 
Is there particular interpolation method or algorithm? 
thank you

**Comment by sjtuytc** [comment]
I'm not sure what empty areas mean but if you mean the masked areas, you can simply ignore them for training.

**Comment by tersite1** [comment]
> I'm not sure what empty areas mean but if you mean the masked areas, you can simply ignore them for training.
Thanks for replying immediately, I have another question
Then, when visualize Block-NeRF, did they use pre-trained model? (Panoptic Deeplab) or train the model again for this research?
