### ISSUE TITLE
A question about the c2w matrix for San Fran Cisco Mission Bay dataset

### ISSUE THREAD

**Issue by SunHongyang10** [dvlab-research/BlockNeRFPytorch#143]
Hello, thanks for making this repository public, and providing the processed block_nerf dataset! I have a question about the c2w matrix. 
I'm curious if you have done any preprocessing on your c2w matrix, because when I tried to run this data set with other codes, the effect was not ideal, but when I multiplied the translation amount of c2w by 20, the effect was significantly improved. I searched for some information and found that some workers do some scaling of the c2w matrix. I wonder if you have done any preprocessing of the c2w matrix in the original data set?
Thank you!

**Comment by SunHongyang10** [comment]
您好！很感谢您的分享！我有一个关于San Fran Cisco Mission Bay dataset的问题！
我好奇您数据集中的c2w矩阵是不是做过什么预处理，因为我尝试用别的代码跑这个数据集时，效果并不理想，但当我将c2w的translation scale*20后，效果有明显的提高。我查找了一些资料，发现一些工作者确实会对c2w矩阵做一些scale的缩放处理，我想知道您是否对原数据集中的c2w矩阵做过一些预处理？
再次感谢您的分享！祝您新年快乐

**Comment by sjtuytc** [comment]
Hi, we don't manually change the data and it's good to share this information to the community. Thank you.
