### ISSUE TITLE
About waymo dataset download

### ISSUE THREAD

**Issue by DRosemei** [dvlab-research/BlockNeRFPytorch#17]
Thanks for your great work! Could you please provide google drive links for waymo dataset, because I cannot download it with 'gdown --id". Thanks in advance!

**Comment by ghost** [comment]
You can provide an email address and I will send you my processed dataset directly, but note that I pre-processed it considering the original dataset is too large, including operations such as extracting bit pose and down_scale, you can use it for testing first

**Comment by sjtuytc** [comment]
Thanks. You can directly view the source of the readme. Pytorch version: https://drive.google.com/file/d/1U7wcE5r-kWtUBscljjTn6q18E8E8kJTd/view
Original version of waymo: https://drive.google.com/file/d/1iRqO4-GMqZAYFNvHLlBfjTcXY-l3qMN5/view

**Comment by sjtuytc** [comment]
The docs would be updated in the next version.

**Comment by DRosemei** [comment]
> You can provide an email address and I will send you my processed dataset directly, but note that I pre-processed it considering the original dataset is too large, including operations such as extracting bit pose and down_scale, you can use it for testing first

Thanks! My email address is rose2497625356@bupt.edu.cn
