### ISSUE TITLE
How to train on pytorch_block_nerf_dataset or convert it to mega-nerf format

### ISSUE THREAD

**Issue by MiZhenxing** [dvlab-research/BlockNeRFPytorch#18]
Hello, many thanks for your great work!
I found that the pytorch_block_nerf_dataset is not in a format similar to mega-nerf. I don't know whether this dataset could be directly used for training by your codes. Could you provide several hands-on commands for that? If it could not be directly trained, could you give some hints on how to convert it to mega-nerf format? Thank you very much!

**Comment by sjtuytc** [comment]
I'm still working on the data formatting issues. Ideally, in one week or two, we would benchmark these two algorithms into one uniform structure.

**Comment by MiZhenxing** [comment]
Got it!
