### ISSUE TITLE
What difference btw Block-nerf and Mega-nerf

### ISSUE THREAD

**Issue by HungNgoCT** [dvlab-research/BlockNeRFPytorch#22]
Hi,

I am wondering that what is the difference between Block-nerf and Mega-nerf?

Thanks and regards,

Hung

**Comment by sjtuytc** [comment]
We are benchmarking the two algorithms and supporting all the datasets. At that time, one can clearly observe the difference.
You may refer to the Mega-nerf's authors' post: https://github.com/cmusatyalab/mega-nerf/issues/23

**Comment by HungNgoCT** [comment]
Thank you, sjtuytc.

Did you mean that this work is for benchmarking the two algorithms? If right, I got your work now. Because I see that the title is BlockNerf for Pytorch, I think this is the code for Block-nerf.

Thank you for your clarification.

Cheers.

**Comment by sjtuytc** [comment]
Sure, the ultimate goal should be the large-scale neural radiance fileds. But Block-NeRF is easy to search and remember so we keep this name. This repo is not restricted to the original Block-NeRF algorithm but is heading towards a system such as Detectron2.

**Comment by HungNgoCT** [comment]
Thank you Sjtuytc.

**Comment by sjtuytc** [comment]
I close this issue temporally and please re-open if the above solution does not address your problem.

**Comment by kwea123** [comment]
So where is the BlockNeRF implementation? I don't see any module about "learned pose refinement", "exposure", or "visibility prediction" which are the main contributions of the paper. All I see is just copy pastes from Mega-NeRF (and from DVGO). Of course you are free to use whatever name you want, but you're using the original BlockNeRF's abstract and video in the README! Then people come here but find nothing of the real BlockNeRF (or they just use without noticing)???

I apologize if I'm wrong, but what I see here is just nothing more than a clickbait without any authentic content.
