### ISSUE TITLE
About training on waymo dataset

### ISSUE THREAD

**Issue by jinyummiao** [dvlab-research/BlockNeRFPytorch#28]
Hi, Thanks for your great works! 
I have downloaded your preprocessed waymo dataset `pytorch_block_nerf_data.zip` and run the code to generate the masks for training following your instructions. However, the code throw an error about missing `corrdinate.pt`. Could you give some advice about this problem? Is the official waymo dataset necessary for training?
Looking forward to your reply. 
Thanks.

**Comment by sjtuytc** [comment]
[coordinates.pt.zip](https://github.com/dvlab-research/BlockNeRFPytorch/files/9466503/coordinates.pt.zip)
Thanks for your attention! Here is the coordinates.pt. You can create it via the latest data_preprocess/fetch_data_from_tf_record.py.
Besides this, we will provide the whole training materials soon.

**Comment by sjtuytc** [comment]
At this version, you need to download the original dataset but things will be changed after a few days.

**Comment by jinyummiao** [comment]
Thanks for your quick reply! looking forward to your updates.
