### ISSUE TITLE
你好，你计划什么时候完成blcok-nerf的全部工作，谢谢

### ISSUE THREAD

**Issue by yushengjiexy** [dvlab-research/BlockNeRFPytorch#29]
你好，你计划什么时候完成blcok-nerf的全部工作，谢谢

**Comment by ghost** [comment]
已经完成了，在整理代码，效果在首页上可以看到

**Comment by yushengjiexy** [comment]
那什么时候发布，有计划吗

**Comment by sjtuytc** [comment]
欢迎保持关注

**Comment by yushengjiexy** [comment]
恩，谢谢。
我查看blcok-nerf，觉得它是通过图像上构建loss来优化相机位姿。这和传统的通过colmap来优化相机位姿好像不太一样，你们是怎么理解的？期待你们的答复，谢谢！

**Comment by ghost** [comment]
nerf的主要任务不是位姿估计。。。他是利用colmap实现的位姿来进行高分辨率的三维重建任务

**Comment by yushengjiexy** [comment]
那它摘要里写了，加了学习型位姿优化
![origin_img_v2_060ca6b3-8bcb-4b04-8178-a40f5fd27bbg](https://user-images.githubusercontent.com/63044657/188582161-d0b05ed8-b65a-4164-8485-eb430b32054a.png)

**Comment by ghost** [comment]
他是借鉴了NeRF--里面的一个技术来优化渲染效果，但是位姿估计并不是NeRF的主要目的，而是一种辅助手段

**Comment by ghost** [comment]
并且位姿优化并不是这篇论文里面的核心技术

**Comment by yushengjiexy** [comment]
恩，你说的对。
我就是想知道它是怎么得到准确的相机位姿的，因为nerf++用了colmap，mega-nerf用了pixel-perfect-sfm来优化相机位姿。实际在我们自己的数据集上，测试发现相机位姿并不能保证准确，需要refine。

**Comment by ghost** [comment]
这是nerf--的工作，你可以去了解一下，并且谷歌数据集尽管没有提供位姿数据(直接给rays也可以完成nerf)，但是你可以通过一些优化方法来求得真实的位姿

**Comment by yushengjiexy** [comment]
哦，多谢答复。
那你认为block-nerf是怎样得到相机位姿的呢，你了解吗？

**Comment by ghost** [comment]
我问过作者，他说是用的colmap，论文里面似乎也有提，你可以去看看补充材料部分

**Comment by yushengjiexy** [comment]
谢谢！
