### ISSUE TITLE
训练自己的数据时config参数如何设置

### ISSUE THREAD

**Issue by guijuzhejiang** [dvlab-research/BlockNeRFPytorch#30]
非常感谢大佬的无私分享。想训练自己的数据，但不知到config要怎么写，下面是configs/custom/Otobai.py的一部分，大佬能给点指导吗？感谢，感谢
factor=2,
movie_render_kwargs={
    'scale_r': 0.8,
    'scale_f': 10.0,
    'zrate': 6.0,
    'zdelta': 0.5,
}

**Comment by sjtuytc** [comment]
可以先试试默认的参数，然后逐渐调整，这个没有统一的规律，我看群里说的是一开始的尺寸可以长一点，结合点云可视化进行预判，然后再精细调整。

**Comment by guijuzhejiang** [comment]
@sjtuytc 感谢回复，能否拉我进群学习，另外您说的“开始的尺寸可以长一点”，请问具体指哪个参数？提前感谢

**Comment by sjtuytc** [comment]
qq: 706949479
far/near

**Comment by guijuzhejiang** [comment]
收到，谢谢
