### ISSUE TITLE
About the intrinsics of Block-Nerf

### ISSUE THREAD

**Issue by FanLu97** [dvlab-research/BlockNeRFPytorch#32]
Hello,
Thanks for your effort for reproducing Block-Nerf.
I use the scripts in fetch_data_from_tf_record.py to generate dataset for Block-Nerf. I observed that you use the proposed intrinsics to generate rays in camera coordinate (Line 133) while the output intrinsics (fx, fy) are the provided intrinsics + [W/2, H/2] (Line 145). It is confusing and could you explain it for me?

Thanks again.

**Comment by sjtuytc** [comment]
It should be a bug. Thanks. Interestingly this key is not used so far. Therefore I did not discover it.
It will be recovered by the next PR.

**Comment by sjtuytc** [comment]
@all-contributors please add @FanLu97 for bug

**Comment by sjtuytc** [comment]
Addressed in the latest PR.
Please reopen if the above solutions do not address your problems.
