### ISSUE TITLE
Where is the pretrained block-nerf model weights on waymo dataset

### ISSUE THREAD

**Issue by MaybeShewill-CV** [dvlab-research/BlockNeRFPytorch#36]
Can not find pretrained model weights via https://drive.google.com/drive/folders/1Lcc6MF35EnXGyUy0UZPkUx7SfeLsv8u9 in README file? Could you please tell me where to find them?

**Comment by sjtuytc** [comment]
https://drive.google.com/drive/folders/1O7uzcPBQHNAcmAcmcS6TRbLqiIDE3D0y?usp=sharing

**Comment by MaybeShewill-CV** [comment]
@sjtuytc Thanks a lot. Besides I have found some small mistakes in https://github.com/dvlab-research/LargeScaleNeRFPytorch/blob/e9949a409fde6ff6ac9260c777ef7d7eaa9c93d1/block_nerf/waymo_dataset.py#L329-L331 when running eval_block_nerf.py script the cam pose was stored in self.img_info['c2w'] rather than self.img_info['transform_matrix'].

**Comment by MaybeShewill-CV** [comment]
@sjtuytc Could you please tell me how to solve this
![Screenshot from 2022-09-14 15-44-23](https://user-images.githubusercontent.com/15725187/190093111-a9c74816-2eac-4c1f-9b18-c7e4d4186bdc.png)

**Comment by sjtuytc** [comment]
You can set exposure_embeddings=True to load the previous model, which will be fixed in the next version.

**Comment by MaybeShewill-CV** [comment]
@sjtuytc Sorry can not find the params in the project ==!

**Comment by sjtuytc** [comment]
https://github.com/dvlab-research/LargeScaleNeRFPytorch/blob/d0ae2bc6327f1248f990aea1d22baad314a05709/block_nerf/block_nerf_model.py#L86

**Comment by MaybeShewill-CV** [comment]
@sjtuytc Thanks. Problem solved. Looking forward to the result:)

**Comment by sjtuytc** [comment]
@all-contributors please add @MaybeShewill-CV for bug
