### ISSUE TITLE
Training anomalies exist

### ISSUE THREAD

**Issue by RuiYangQuan** [dvlab-research/BlockNeRFPytorch#4]
hi,Thanks for your excellent work, but I get stuck in some places when I train the module, when the video memory is occupied, but no gpu is called to participate in the calculation, I don't know how to deal with this situation, I hope you can give some advice
![9-1](https://user-images.githubusercontent.com/90050796/183618427-381150a1-08ab-485e-b0bc-c9197360353b.png)
.

**Comment by sjtuytc** [comment]
Hi, would you mind pressing ctrl + C to stop the program and providing the screenshot to help diagnose where it stops?

**Comment by RuiYangQuan** [comment]
> Hi, would you mind pressing ctrl + C to stop the program and providing the screenshot to help diagnose where it stops?

This is the message after the screenshot
![10-1](https://user-images.githubusercontent.com/90050796/183791823-ba672fc3-829f-45bd-b3c4-3ff87ecf1de4.png)

**Comment by sjtuytc** [comment]
It seems that the CUDA built has some issues. Please ensure your Pytorch version and CUDA lib version are compatible.
After that, see [this issue](https://github.com/sunset1995/torch_efficient_distloss/issues/3) and this [post](https://discuss.pytorch.org/t/freezing-at-using-home-user-cache-torch-extensions-as-pytorch-extensions-root/132759/6).

**Comment by sjtuytc** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/31123348/183796115-7468d0b0-461a-43cd-803a-d8c768d16611.png">

**Comment by sjtuytc** [comment]
I close this issue temporally and please re-open if the above solution does not address your problem.
