### ISSUE TITLE
深度图无法直接合成视频

### ISSUE THREAD

**Issue by kuguaqing** [dvlab-research/BlockNeRFPytorch#40]
eval_block_nerf.py里面，depth_video_writer.write(Depth_compose['compose'])，直接将1通道的深度图写入视频，我发现结果视频都没法播放，好像是因为cv2.VideoWriter没法直接将1通道的图片合成视频，需要先转为3通道，所以我在前面加了Depth_compose['compose'] = cv2.cvtColor(Depth_compose['compose'],cv2.COLOR_GRAY2BGR)，就可以成功转成视频了。

**Comment by sjtuytc** [comment]
我这边没注意到这个问题，下个版本我尝试修复一下，谢谢。
