### ISSUE TITLE
waymo Dataset :No such file or directory: 'data/pytorch_waymo_dataset/train/rgbs/1194311609.png'

### ISSUE THREAD

**Issue by lishulincug** [dvlab-research/BlockNeRFPytorch#42]
I downLoad the waymodataset from https://drive.google.com/drive/folders/1Lcc6MF35EnXGyUy0UZPkUx7SfeLsv8u9, run
export BLOCK_INDEX=0
bash scripts/block_nerf_train.sh ${BLOCK_INDEX}  ,but has a promblem.
![image](https://user-images.githubusercontent.com/13003282/197922149-2779a0cd-a379-48a9-9546-06a35ee1c736.png)

**Comment by sjtuytc** [comment]
Hi, thanks for your attention. I confirm that this image might be missing from the zip folder (as I've been working on the ordered split for a long time, I did not look into this). Would you mind trying to download the v1.0 raw dataset and trying to extract it by yourself?

**Comment by lishulincug** [comment]
Thanks！

**Comment by ITBoy-China** [comment]
> I downLoad the waymodataset from https://drive.google.com/drive/folders/1Lcc6MF35EnXGyUy0UZPkUx7SfeLsv8u9, run export BLOCK_INDEX=0 bash scripts/block_nerf_train.sh ${BLOCK_INDEX} ,but has a promblem. ![image](https://user-images.githubusercontent.com/13003282/197922149-2779a0cd-a379-48a9-9546-06a35ee1c736.png)

@lishulincug 您好，我也碰到了这个问题。看作者的回复是让我们自己去下载`waymo dataset v1.0`的数据是吗，然后自己去处理的需要的数据格式？您这边有处理好的数据吗？方便分享一下吗？感激不尽！！！

**Comment by lishulincug** [comment]
数据19Gb呀，会不会太大了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月1日(星期二) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dvlab-research/LargeScaleNeRFPytorch] waymo Dataset :No such file or directory: &#39;data/pytorch_waymo_dataset/train/rgbs/1194311609.png&#39; (Issue #42)





  
Thanks！
   
I downLoad the waymodataset from https://drive.google.com/drive/folders/1Lcc6MF35EnXGyUy0UZPkUx7SfeLsv8u9, run export BLOCK_INDEX=0 bash scripts/block_nerf_train.sh ${BLOCK_INDEX} ,but has a promblem. 
  
@lishulincug 您好，我也碰到了这个问题。看作者的回复是让我们自己去下载waymo dataset v1.0的数据是吗，然后自己去处理的需要的数据格式？您这边有处理好的数据吗？方便分享一下吗？感激不尽！！！

**Comment by ITBoy-China** [comment]
> 数据19Gb呀，会不会太大了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月1日(星期二) 下午2:24 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [dvlab-research/LargeScaleNeRFPytorch] waymo Dataset :No such file or directory: &#39;data/pytorch_waymo_dataset/train/rgbs/1194311609.png&#39; (Issue #42) Thanks！ I downLoad the waymodataset from https://drive.google.com/drive/folders/1Lcc6MF35EnXGyUy0UZPkUx7SfeLsv8u9, run export BLOCK_INDEX=0 bash scripts/block_nerf_train.sh ${BLOCK_INDEX} ,but has a promblem. @lishulincug 您好，我也碰到了这个问题。看作者的回复是让我们自己去下载waymo dataset v1.0的数据是吗，然后自己去处理的需要的数据格式？您这边有处理好的数据吗？方便分享一下吗？感激不尽！！！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

如果您方便的话，可以通过百度网盘share一下，或者您加我联系方式，咱也方便交流
我微信号码：`z18827468069`
