### ISSUE TITLE
4.3 Train sub-modules.这一步的输出是什么呀，整个项目最后的输出结果是什么呢？

### ISSUE THREAD

**Issue by lishulincug** [dvlab-research/BlockNeRFPytorch#43]
4.3 Train sub-modules.这一步的输出是block-nerf的网络模型权重参数？，没有三维场景模型或者视频输出吗？后面也没看到街景建模的三维场景模型，最后的生成只是三维场景的视频？

**Comment by sjtuytc** [comment]
你好，应该没有你说的所谓三维模型，BlockNeRF不是做这个事儿的

**Comment by sjtuytc** [comment]
Closed because of no response.
