### ISSUE TITLE
No such file or directory train_block_nerf.py

### ISSUE THREAD

**Issue by xiaoxiaolu1111** [dvlab-research/BlockNeRFPytorch#45]

**Comment by sjtuytc** [comment]
The original implementations of block-nerf are removed due to license issues. I will later upload a newer version of Block-NeRF implementations with stronger performances.

**Comment by yzslab** [comment]
> The original implementations of block-nerf are removed due to license issues. I will later upload a newer version of Block-NeRF implementations with stronger performances.

Looking forward to your update!

**Comment by JonasW-byte** [comment]
> The original implementations of block-nerf are removed due to license issues. I will later upload a newer version of Block-NeRF implementations with stronger performances.

Hi, I have trained block nerf in last version by my own dataset, but the depth image i.e depth information has a bad performance.Exactly to say, there is almost no depth information. Is there any advice to train the model?

**Comment by a15097916856** [comment]
Looking forward to your update!

**Comment by GuoPingPan** [comment]
Greatly looking forward to your update，I deadly want to understand this job.

**Comment by jnskkmhr** [comment]
@sjtuytc 

Thank you for your great work. 
Do you have plans on when to republish your BlockNeRF training scripts ?

**Comment by sjtuytc** [comment]
Before ICCV deadline. However, I have to say the methodology is quite different from the block nerf paper.

**Comment by jnskkmhr** [comment]
@sjtuytc 
Thank you so much for quick response.
Looking forward to your update !

**Comment by sjtuytc** [comment]
Code is released now.
