### ISSUE TITLE
Splitting data with known camera pose into seperate blocks

### ISSUE THREAD

**Issue by olestole** [dvlab-research/BlockNeRFPytorch#46]
**I'm trying to generate a Block-NeRF with my own data**

How would you proceed if you were to split your own data into separate blocks, in order to train them with `train_block_nerf.py`? `split_block.py` can't run on custom data because of lacking files such as `train_all_meta.pt` and `split_block_train.json` which are included in Waymo's data. Is there a way to generate these required files?

**Comment by sjtuytc** [comment]
A general suggestion in the practice is that you can just split the training indexes on the fly and train each block independently while only loading the indexes in the current training block. You don't have to split the blocks prior to the NeRF training.

**Comment by olestole** [comment]
Okay, thanks for responding! So you would 
- feed all the images to train_block_nerf.py, 
- create a pre_processing-step for splitting the data into separate NeRFs, 
- train on a single split

The issue arises when you want to evaluate the block NeRF. In your prior implementation you define `split_block_train.json` which contains info about the elements of each nerf and their relative distances. How would you do this on the fly?

**Comment by sjtuytc** [comment]
just cal_distance:calculate every co distance to the local centers.
split_indexs according to the distances and divide into blocks.
Then only load the index of interests.

**Comment by sjtuytc** [comment]
Closed because of no response.
