### ISSUE TITLE
How to get camera extrinsic of the BlockNeRF dataset?

### ISSUE THREAD

**Issue by zymeng1994** [dvlab-research/BlockNeRFPytorch#5]
I have tried colmap, but I meet the error "ERROR: the correct camera poses for current points cannot be accessed".

Thanks for your time.

**Comment by ghost** [comment]
You can try a simple way as followed, I just tried normalizing the rays_dir in the camera coordinate system and then based on the normalized rays_dir offered by the waymo datasets, we can establish the equation of rays_norm_dir_world=R*rays_norm_dir_cam, this is a superdeterminant equation, and just solve it, after that u can get the proper camera poses.  It is worth noting that, despite the simplicity of this method, the average error obtained from the test can reach 1e-5~1e-6

**Comment by zymeng1994** [comment]
Thanks!

**Comment by ghost** [comment]
If u still can't figure it, u can email me at zesongyang0@gmail.com that I can share u with my script

**Comment by zymeng1994** [comment]
Thank you very much. I have emailed you.

**Comment by sjtuytc** [comment]
The detailed scripts with visualizations will be released soon. Thanks and welcome to add my Wechat: ytc407 for coorperation.

**Comment by sjtuytc** [comment]
@all-contributors please add @SEUleaderYang  for providing the camera pose estimation scripts

**Comment by sjtuytc** [comment]
@all-contributors please add @SEUleaderYang for code

**Comment by sjtuytc** [comment]
@all-contributors please add @sjtuytc for code

**Comment by sjtuytc** [comment]
https://github.com/all-contributors please add @sjtuytc for maintenance

**Comment by sjtuytc** [comment]
@all-contributors please add @sjtuytc for maintenance
