### ISSUE TITLE
Why use the transpose matrix of the cam_to_world rotate matrix?

### ISSUE THREAD

**Issue by rockywind** [dvlab-research/BlockNeRFPytorch#50]
Hi, 
Why use the transpose matrix of the cam_to_world rotate matrix in the [line](https://github.com/dvlab-research/LargeScaleNeRFPytorch/blob/484baabef72d06edba2b39a3e24e0234244f728f/block_nerf/waymo_dataset.py#L29)?
I remember the transpose matrix of a rotate matrix is equal to the inverse matrix. The inverse matrix is the mean from the world coordinate to the camera coordinate. 
![image](https://user-images.githubusercontent.com/14838781/207281886-1a868fae-b639-49ef-a021-d4e0677a85eb.png)

**Comment by sjtuytc** [comment]
Well, I guess this line is not used. I am currently working based on DVGO, where the get_rays function automatically utilize c2w, and the transpose is not used. Hope this can help you.

**Comment by rockywind** [comment]
Thanks a lot!
