### ISSUE TITLE
How to get the real world scale depth?

### ISSUE THREAD

**Issue by rockywind** [dvlab-research/BlockNeRFPytorch#52]
Hi,
I found the depth value is a normalize between 0 and 1 when I debug the inference code.
How to get the real world scale depth?
![image](https://user-images.githubusercontent.com/14838781/212597331-b275a702-6e84-4244-86a9-369b0a67830d.png)

**Comment by sjtuytc** [comment]
I think you need to reverse the coordinates into the real world coordinates. Normally this is not needed because the depth is only for visualization purposes.

**Comment by rockywind** [comment]
Hi, 
How to reverse the coordinates into the real world coodinates?
I want to use the depth map to generate the pseudo point clouds.
I found some [advises](https://github.com/sunset1995/DirectVoxGO/issues/28) like below, but I can't understand the t_min and stepdist,
so I need some help.
![image](https://user-images.githubusercontent.com/14838781/212891644-0acb560e-9944-4cbb-9880-fa8c1f9d4fba.png)

**Comment by sjtuytc** [comment]
I'm sorry, but I have no experience with this.  It is beyond the scope of this repo.

**Comment by rockywind** [comment]
Thanks a lot!

**Comment by rockywind** [comment]
Hi, 
Can I get the scene point cloud from the NeRF result?
Just like below.
![image](https://user-images.githubusercontent.com/14838781/213385917-2c4bf32a-c35b-46f9-8bf6-40c32ea774d5.png)

**Comment by sjtuytc** [comment]
Sure, you need to refer to other repos.

**Comment by rockywind** [comment]
Thanks a lot.
Can you recommend other repos for generating the scene point cloud?

**Comment by sjtuytc** [comment]
I have no experience with this. Probably you can look into NeRF++ or DVGO or Plenoxels.

**Comment by rockywind** [comment]
Thanks a lot!

**Comment by ChenLu-china** [comment]
I can give you some advice.
1. If you want to get the point from a view, you can calculate pc = camera_o + t * camera_d, so t_min means the begin of t;
2.  why the depth between [0, 1], you can reference grid coordinate to world cooredinate.

**Comment by rockywind** [comment]
Hi, @ChenLu-china 
Thanks!, Is there any example code for reference?
