### ISSUE TITLE
improvement of depth info

### ISSUE THREAD

**Issue by JonasW-byte** [dvlab-research/BlockNeRFPytorch#55]
Hi, do u have any engineering experience for improving the depth training.if the pose is correct, do I need tune the params?

Here i got in own dataset by default setting
![image](https://user-images.githubusercontent.com/33064930/213384859-9723468c-ccdb-45a7-bd03-e543b0cb4803.png)
Here from pretrained model in supported dataset
![image](https://user-images.githubusercontent.com/33064930/213384919-bfa3f3bd-b6dc-49a5-b25b-598ff9f4eebf.png)

**Comment by sjtuytc** [comment]
It's a mixed problem. A short checklist:
(1) Make sure the scenes are forward-facing. That means the camera should march like a crab. The normal forward-moving (not forward-facing) scenes can be quite hard for NeRF.
(2) Optimization practices of the existing literature on bounded scenes simply do not work for unbounded scenes. I'm writing a paper on this, and the short suggestion is the simplest optimization strategy works the best.
(3) The most important hyperparameters are those related to the scene geometry, where you need to determine the relationship between NeRFs, cameras, and objects. Specifically, the scene box, near/far, etc.
