### ISSUE TITLE
custom dataset preparation

### ISSUE THREAD

**Issue by vinodrajendran001** [dvlab-research/BlockNeRFPytorch#57]
The existing NeRF papers illustrated that we can use COLMAP to generate ```transform.json``` file. However, it comes with a condition that there should be 70% overlap with each images.

In Block-NeRF, they mentioned that image data captured from 12 cameras that collectively provide a 360° view. 8 of the cameras provide a complete surround view from the roof of the car, with 4 additional cameras located at the vehicle front pointing forward and sideways.

Would it be possible to share the piece of code that used those 12 camera images as input to generate a ```transform.json``` ?

Many thanks.

**Comment by sjtuytc** [comment]
This part is very tricky. I don't think the Google teams use the same type of COLMAP because I often find that our COLMAP produces very weak poses while they still get strong poses. Probably they have an internal version of COLMAP, or they use an additional refinement procedure.

So the short answer is, I don't know this.

**Comment by vinodrajendran001** [comment]
Understand. Do you happen to know any repo which shares details on how to generate a ```transform.json``` without using COLMAP or any third party tools?

**Comment by sjtuytc** [comment]
Can you check HLoc? It's a state-of-the-art camera relocation lib. I tried it once, and its performance is good. The only issue is that you have to program for a while.

**Comment by vinodrajendran001** [comment]
Thanks for the info. Hope you are referring to this [repo](https://github.com/cvg/Hierarchical-Localization)

**Comment by sjtuytc** [comment]
Yep.
