### ISSUE TITLE
rendering_video error

### ISSUE THREAD

**Issue by galgaxy** [dvlab-research/BlockNeRFPytorch#58]
when i generate a fly-through video it make success, but when i download it and open cause file damage? I dont know what's wrong, could you help me?

**Comment by sjtuytc** [comment]
1. Output the images and see whether the images are OK. If OK, you can turn them into videos via ffmpeg.
2. If the output images are damaged, check your rendering codes.

**Comment by galgaxy** [comment]
Thx. I fix this by using ffmpeg
