### ISSUE TITLE
How to get a sequential list of training frames per camera (preprocessed waymo dataset)?

### ISSUE THREAD

**Issue by deepshwang** [dvlab-research/BlockNeRFPytorch#59]
I really appreciate for making this repo public!

I was wondering how to get a "sequential" list of trainings per camera (out of 12 cameras).

Here is how I understood the data framework and tried to get a sequential list of images:
- the data has been preprocessed by globing the original data by its filename (which I assumed to include sequential information). 
- The preprocessing script recorded this globbed sequence using 'index' key in metadata dictionary.
- Meanwhile, each image is captured from one of 12 cameras, whose index is stored as 'cam_idx' in metadata dictionary.
- So, I sub-sampled images with same 'cam_idx' per block, and ordered them by 'index'.

This gave me pretty random sequence of images... any hints on retrieving clean sequence as in "oct2_124_300_frames_trim.mp4" video that shows training frames sequentially in the README.md?

Thank you in advance!

**Comment by sjtuytc** [comment]
Just sorting the ray origins can help you out.
