### ISSUE TITLE
Big dataset

### ISSUE THREAD

**Issue by RuiYangQuan** [dvlab-research/BlockNeRFPytorch#6]
hi,i have a questions ,how to implement the parallel training and merging function in blocknerf when it needs to run large dataset?

**Comment by ghost** [comment]
You can try using pytorch-lightning to implement train.py, it will automatically load the data onto multiple GPUs according to the number of GPUs you set.  Once you have sliced and diced the entire waymo dataset, the data used in a block is generally on the order of 1e3, and if you still find this large, try sampling the data randomly

**Comment by sjtuytc** [comment]
Actually, this is the main difficulty in block-nerf and it's hard to answer via one sentence. Basically, you need CUDA parallelization, vectorization, and python multi-processing. We found the combination of these techniques can shorten the training time to a reasonable number. 
You can add my WeChat ytc407 to join our reproduction group.

**Comment by sjtuytc** [comment]
I close this issue temporally and please re-open if the above solution does not address your problem.
