### ISSUE TITLE
Some error when I eval the pretrained models

### ISSUE THREAD

**Issue by szgy66** [dvlab-research/BlockNeRFPytorch#60]
Hi, First of all thank you for your great work. 
When I was about to train the block-nerf model on my own data set, I followed your advice and validated it on the data set you provided and the pre-training model, but when I ran: **bash scripts/block_nerf_eval.sh**. The following error occurs:
![image](https://user-images.githubusercontent.com/46223162/218357256-0d279176-31dd-4a8c-82a8-7c634e23b12c.png)
I check the **block_nerf file** in the project, I do not find related function, including block_nerf_model、block_nerf_lightning. I guess there is something wrong with the environment. Can you help me? Thanks.

**Comment by JonasW-byte** [comment]
It's already removed. You can check more info in #45.

**Comment by sjtuytc** [comment]
Yes. I'll release a new version with better quality in a few days.

**Comment by sjtuytc** [comment]
Closed because of duplicated issue. Thanks for your interests.
