### ISSUE TITLE
How to use the code vis_volume.py?

### ISSUE THREAD

**Issue by xiehousen** [dvlab-research/BlockNeRFPytorch#61]
I think this code is used to visualize mesh, but how should this code be used? How to generate mesh data?

**Comment by sjtuytc** [comment]
Exactly. Please refer to DVGO official code for support on this. We are not using this kind of analysis because the 3D point cloud looks messy and unclear. Also it is not for general NeRFs.

**Comment by xiehousen** [comment]
Are you talking about the floaters in NeRF?

**Comment by sjtuytc** [comment]
Not exactly. It's normal to see cloudy volumes, even though the renderings are perfect. You can find this out by seing the visualizations of DVGO.

**Comment by xiehousen** [comment]
Will this situation be particularly obvious in large scenes?

**Comment by sjtuytc** [comment]
Sure. More particular.
