### ISSUE TITLE
No module named 'block_nerf.rendering'

### ISSUE THREAD

**Issue by ghaodong** [dvlab-research/BlockNeRFPytorch#62]
hi, thanks for this great work for large scene.
I'm a Chinese college student, when I want to reproduce your block-nerf, run "bash scripts/block_nerf_eval.sh" and say "No module named block_nerf.rendering", there is really no rendering.py under block-nerf, didn't you put it up?

**Comment by sjtuytc** [comment]
Refer to the existing issue. Code will be ready in a few days.

**Comment by sjtuytc** [comment]
Closed because of duplicated issue #45 .
