### ISSUE TITLE
Question about the imgs2pose.

### ISSUE THREAD

**Issue by xiehousen** [dvlab-research/BlockNeRFPytorch#63]
When I run this code on Madoka, I meet this problem. The bin file doesn't generate, So the code raise the error FileNotFoundError.

https://github.com/sjtuytc/LargeScaleNeRFPytorch/blob/d6e7371d4c11227711e021a30ff43f300fdcf8bb/tools/colmap_utils/pose_utils.py#L15

**Comment by sjtuytc** [comment]
What are your files under realdir? Different versions of COLMAP give you different output file structures.

**Comment by xiehousen** [comment]
The realdir is datasets/Madoka.

**Comment by sjtuytc** [comment]
Yes, then where are your cameras.bin? If you cannot find the output of COLMAP, you can visit the official repo of COLMAP. They will give you support.

**Comment by sjtuytc** [comment]
Closed because of no response.
