### ISSUE TITLE
Preparing data for training from existing colmap model

### ISSUE THREAD

**Issue by Zador-Pataki** [dvlab-research/BlockNeRFPytorch#64]
Hi, I have an existing city-scale (1km by 1km) colmap model of 20'000 grayscale images with well refined poses. I am a bit lost on how to train using this data. 

How do I convert this into the format required for training? I have cameras.bin, images.bin, points3D.bin and the corresponding images. Additionally, what config file do you recommend for such a scenario? Finally, I suspect not, but does this project support sparse depth supervision?

**Comment by sjtuytc** [comment]
Thanks for your interests in our repo. You can extract cameras.bin into COLMAP. You can refer to the "custom" section in the repo of DVGO. As for the config, it is recommended to try the default parameters. If it is convenient to you, you can publish sample data to a Google drive and I can take a look into it to give you concrete suggestions. The sparse depth supervision is not involved, although it is a potential idea to improve the performance.

**Comment by Zador-Pataki** [comment]
Hi thanks, checked out the section mentioned in DVGO and it works. Haven't gotten around to testing things out with the default config, but I think this issue can be closed.

**Comment by hvkwak** [comment]
Hello @sjtuytc @Zador-Pataki, I'm kinda late to this party. I'd like to train my custom dataset on Block-NeRF.  I was unable to find the "custom" section in the repo of DVGO. I've got two questions regarding datasets: 1) Will there be a press-enter-and-go script to convert colmap outputs for `fetch_data_from_tf_record.py`? 2) If not, my understanding is that we run `fetch_data_from_tf_record.py` to produce pytorch files and split block using `split_block.py`. Will there be a specific coordinate system convention I have to keep in mind? I guess it is similar to MegaNeRF. e.g.) MegaNeRF assumes that the coordinate system is in DRB(with basisvectors of RDF) followed by this operation on its rotation matrix in c2w: https://github.com/cmusatyalab/mega-nerf/blob/76d8d76b66d70f8a0819defc0cef4fb9aa251672/scripts/colmap_to_mega_nerf.py#L409

**Comment by sjtuytc** [comment]
Thanks for your attention. The poses are from the original block nerf paper and I think the format does not matter.

**Comment by hvkwak** [comment]
Thank you for a quick reply. Ok. I will see what I can do.
