### ISSUE TITLE
运行run_FourierGrid.py报错出现Process finished with exit 139（interrupted by signal 11:SIGSEGV）

### ISSUE THREAD

**Issue by joeyw1030** [dvlab-research/BlockNeRFPytorch#66]
你知道怎么解决么，感谢万分

**Comment by joeyw1030** [comment]
出错的好像是from FourierGrid.load_everything import load_everything

**Comment by sjtuytc** [comment]
有没有截图和上下文，运行命令。
单看这个报错看不出来，我没遇到过。

**Comment by joeyw1030** [comment]
![1677337832182](https://user-images.githubusercontent.com/73374378/221364638-dd457e6e-f9ee-456e-a6aa-eb4eb498465c.jpg)

**Comment by joeyw1030** [comment]
好像是导FourierGrid这个包出现了错误

**Comment by sjtuytc** [comment]
Custom config已经不再支持了暂时，请按推荐指令运行
我没有遇到过段错误，你可以分段运行一下看哪里报错

**Comment by sjtuytc** [comment]
还有个可能是cuda编译的问题，请确认cuda包和pytorch自带cuda匹配，另外重新建立环境编译试试。

**Comment by joeyw1030** [comment]
我安装了11.7的cuda版本 是不是和这个有关系

**Comment by joeyw1030** [comment]
![WX20230225-232258@2x](https://user-images.githubusercontent.com/73374378/221365216-14d55863-3a5a-4daf-9d80-2a24c8ccc079.png)

**Comment by joeyw1030** [comment]
我注意到你的py文件名字似乎与函数的名字相同，是不是出现了引用的错误

**Comment by joeyw1030** [comment]
例如from FourierGrid.load_everything import load_everything 出现了两个load_everything  python代码似乎没有分辨出它们两个

**Comment by sjtuytc** [comment]
你可以简单试试hello.py倒入hello函数，函数和代码名字一样是没问题的，这是python基础，你试试就知道了
如果说是模块有问题，一般报错都是cannot import module: XX
你现在需要定位到是哪一行出了错，你可以一行一行地执行python程序，看哪里出的错

**Comment by sjtuytc** [comment]
我大概率推测你的错误原因是之前编译过，换了机器或者环境，导致你原先编译好的东西现在不能用了。
你需要一台新服务器重新搭建环境试试。

**Comment by sjtuytc** [comment]
Closed because of no response. Plz reopen this issue if it is still not resolved.
