### ISSUE TITLE
Problem when run waymo dataset.

### ISSUE THREAD

**Issue by ProjSender** [dvlab-research/BlockNeRFPytorch#67]
Hiii I met a weird problem when following your recommended commands. Since I have already downloaded the corresponding dataset from the provided google drive link in this repo, the file structure specified in the load_waymo.py might be different. 

When I ran "python run_FourierGrid.py --program train --config FourierGrid/configs/waymo/waymo_no_block.py --num_per_block 100 --render_video --exp_id 30", I got "No such file or directory: 'data/sep19_ordered_dataset/metadata.json'". 

However, I don't think a folder called "sep19_ordered_dataset" exists in pytorch_waymo_dataset. Maybe I miss something and I will appreciate it if you could give some advice.
Thanks:)

**Comment by sjtuytc** [comment]
Thanks for your interests. Can you first try T and T and mipnerf360 benchmark? The waymo dataset has a few problems in doc support, I'll look into it later.

**Comment by ProjSender** [comment]
Sure, thanks for your reply.
