### ISSUE TITLE
waymo dataset 问题

### ISSUE THREAD

**Issue by Miracle1991** [dvlab-research/BlockNeRFPytorch#72]
你好，waymo数据集上的训练大该什么时候会修复呢

**Comment by sjtuytc** [comment]
感谢你的关注，你是说原来的代码吗？原来的已经修复了，你可以看到原来的issue已经关闭。至于最新版本的，应该也是可以跑的，文件代码都有了，就是文档可能缺失了点有的数据处理得自己弄，但是代码都在仓库里。

**Comment by sjtuytc** [comment]
我等过几周弄弄，不过得做好放弃waymo的准备，因为我发现很多相机参数有离谱的错误，难以得到很好的结果。再加上最近有些高质量数据集放出来，我们更感兴趣在好的数据集上测试我们的方法。

**Comment by Miracle1991** [comment]
嗯嗯，感谢你的回答

**Comment by sjtuytc** [comment]
嗯嗯感谢你的理解，我们也是摸着石头过河。

**Comment by sjtuytc** [comment]
Closed because of no further comments.
