### ISSUE TITLE
About 3D mesh

### ISSUE THREAD

**Issue by szgy66** [dvlab-research/BlockNeRFPytorch#73]
很感谢您伟大的工作！最近正在复现你的工作以便将您的方法推广到自己的数据集。我训练并测试360_v2数据集中的room，通过指令：python run_FourierGrid.py --program train --config FourierGrid/configs/nerf_unbounded/room_single.py --num_per_block -1 --eval_ssim --eval_lpips_vgg --render_train --render_test --render_video --exp_id 9. 我确实得到相关的结果，但是可视化的结果只包含相关的视频，本质上说还是二维的。所以我想问是否可以提取结果mesh的ply文件，以便可以三维的展示。谢谢！

**Comment by sjtuytc** [comment]
Thank you a lot for your appreciation! That means a lot to us.
3D mesh construction is another interesting direction; we have not touched on this yet.
Hope you do well in your research!

**Comment by sjtuytc** [comment]
Closed because of no further comments.
