### ISSUE TITLE
Run my own dataset

### ISSUE THREAD

**Issue by szgy66** [dvlab-research/BlockNeRFPytorch#74]
Hello! I want to train my own dataset on your project and I have used colmap to get the necessary files. When I run the command："python run_FourierGrid. Py -- -- config FourierGrid/configs/custom/Madoka. Py - program train - exp_id 10 " (where --program and --exp_id are added by my own reference), but it will give the following error:
![image](https://user-images.githubusercontent.com/46223162/223036674-2b3d527c-41b5-451b-a0aa-65771515f602.png)
How do I do that, or do I have to run the command and there's a problem. Thanks!

**Comment by sjtuytc** [comment]
Thanks for your interest in our repo. This issue means you send twice the argument "num_voxels" to the program. You should be aware that there are many ways to send parameters into the model creator:
(1) parameters in the config file 
(2) parameters in the command line argument
(3) function overwrites in code
You normally should only use one of them to avoid conflicts.

**Comment by sjtuytc** [comment]
Closed because of no further comments.
