### ISSUE TITLE
About sm01_desktop dataset

### ISSUE THREAD

**Issue by szgy66** [dvlab-research/BlockNeRFPytorch#75]
Hello, I am trying to reproduce your project recently. Good results are indeed obtained for the data set 360_v2. I want to try my own data set, so I want to replicate the data set sm01_desktop you provided first. I used colmap to get the relevant data. Running instruction: python run_FourierGrid.py --program train --config FourierGrid/configs/custom/sm01_desktop.py --num_per_block -1  --render_train --render_test --render_video --exp_id 57(Comment out line 39 of run_train.py: num_voxels=num_voxels_rgb, otherwise will raise the error: FourierGrid. Dmpigo. DirectMPIGO () got multiple values for keyword argument 'num_voxels', I think this is a bug). But when it's done, it's pretty bad. Is there something wrong with me? Or the config file of sm01_desktop cannot be used for training sm01_desktop. Looking forward to your reply, thank you!

**Comment by sjtuytc** [comment]
That's a good question. In a nutshell, the forward-facing scenes are quite different from the unbounded scenes.  So you need to run the original DVGO for sm01. We will not support this simple forward-facing scenario currently. 
More analysis of the unbounded scenes will be illustrated in our paper.
