### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by robo-alex** [dvlab-research/BlockNeRFPytorch#78]
Thanks for your impressive work!

I am really excited about it and have been following it for a long while! Would you mind if I contact you for chats and cooperation? Thanks!

**Comment by sjtuytc** [comment]
Thanks for your attention!
I do not have bandit for collaboration now. However, for any concrete technical question, you can always open an issue and I'll look into that.

**Comment by robo-alex** [comment]
Thanks so much!
