### ISSUE TITLE
block nerf  block0训练效果差

### ISSUE THREAD

**Issue by Miracle1991** [dvlab-research/BlockNeRFPytorch#79]
我完成了block0的训练，但是看起来结果比较粗糙
![37_243701827_817492759_block_0](https://user-images.githubusercontent.com/33547384/223975814-f0927959-60ed-4985-b248-6c65cb247daa.png)

请问有什么比较好的经验吗

**Comment by sjtuytc** [comment]
你是说原来的代码吗？我觉得最核心的问题在于pose不准确，然后算法也不是sota了

**Comment by sjtuytc** [comment]
Closed because of no further comments.
