### ISSUE TITLE
Final video result

### ISSUE THREAD

**Issue by ZhangAma** [dvlab-research/BlockNeRFPytorch#80]
I just found that the difference between the render_train_last and render_video_fine_last. How to you achieve this, like the render_video_fine_last, The video is not generated according to the camera position of the image, but it is like generated by human shooting. But the render_train_last is like combine all camera positions and generate the video

**Comment by sjtuytc** [comment]
Thanks for your attention. What do you mean by generating via human shoots? In Block nerf We combine renderings from different blocks together.

**Comment by sjtuytc** [comment]
Closed because of no further comments.
