### ISSUE TITLE
About axtrct 3D mesh

### ISSUE THREAD

**Issue by szgy66** [dvlab-research/BlockNeRFPytorch#82]
Hello, the last few days have proved the superiority of your project in borderless scenarios. I want to convert the generated video into 3D mesh based on this. I studied the implementation of extracting mesh from [nerf_pl](https://github.com/kwea123/nerf_pl). It mainly uses mcubes marching_cubes function to calculate isosurfaces on the sigma(opacity) of the resulting result, which I understand is similar to SDF(sign distance function). When I refer to your project and [DVGO](https://github.com/sunset1995/DirectVoxGO), I find that there is no relevant sigma but a lot of depth information will be designed, especially DVGO will directly generate in-depth videos. So I have two questions:
1. This depth information I think can be understood as SDF, which is the formation of the level surface. Is it possible that this is equivalent to the sigma value in [nerf_pl](https://github.com/kwea123/nerf_pl), which can be used to extract the mesh?
2. If the first statement is not true, what other suggestions do you have?

Thanks!

**Comment by sjtuytc** [comment]
I'm sorry, I don't know SDF or 3D mesh techniques. I'll leave this issue open for several days to see if other experts can help you.
