### ISSUE TITLE
使用FourierGrid在waymo数据集上训练

### ISSUE THREAD

**Issue by 834810269** [dvlab-research/BlockNeRFPytorch#83]
您好，我正在尝试在FourierGrid训练waymo数据集的某个block，我已经对齐了数据格式，但训练效果不好。有以下几个问题：
1.waymo数据集的位姿是否需要归一化，尺度问题
2.初始网格怎么设置，这可能和几个参数有关：near、far、world_bound_scale，以及为什么FourierGrid_compute_bbox_by_cam_frustrm_waymo计算boundingbox只使用了光心坐标，这样会不会voxel grid覆盖的区域过小
3.网格的分辨率如何设置，默认400✖️400✖️400对于大场景会不会太小
期待您的解答

**Comment by sjtuytc** [comment]
感谢你的关注，后续我们会对waymo提供更好的支持，目前来看，
1.waymo数据集自身姿态有问题，特别是大范围的
2.这些参数目前看起来是最优的，虽然你可以尝试更好的参数
3.网络的分辨率在我看来是足够的，你可视化一下就会发现大量网格都是空白的

**Comment by 834810269** [comment]
感谢回复，请问下您指的参数目前是在哪个文件设置的，是FourierGrid/configs/waymo/waymo_no_block.py?
另外就是使用FourierGrid_compute_bbox_by_cam_frustrm_waymo计算boundingbox只使用了光心坐标，这样会不会voxel grid覆盖的前景区域只是光心附近？

**Comment by sjtuytc** [comment]
是的，这其实是个好问题，你可以试试
