### ISSUE TITLE
关于块的划分问题

### ISSUE THREAD

**Issue by joeyw1030** [dvlab-research/BlockNeRFPytorch#85]
你好，我想请问一下如果我想进行分块训练val和test是否也需要预先分块，是所有数据先进行分块在进行（train，val，test）的划分还是先进行数据集的划分再进行分块。

**Comment by sjtuytc** [comment]
感谢你的关注，这个先后顺序是无所谓的，比如都是0-1000的index，那么第512个如果被分到第二块和训练集，那么先分哪个有什么区别呢

**Comment by joeyw1030** [comment]
那如果先进行数据集的划分 那么 train块的中心点 和val的中心点可能会不一样 也就是说 tval block1里面的图片可能不在rain block1里面，这样可以吗

**Comment by joeyw1030** [comment]
那如果先进行数据集的划分 那么 train块的中心点 和val的中心点可能会不一样 也就是说 val block1里面的图片可能不在train block1里面，这样可以吗

**Comment by sjtuytc** [comment]
那这样效果肯定不会好，为什么要这样呢

**Comment by joeyw1030** [comment]
谢谢你的解答

**Comment by joeyw1030** [comment]
但是我用你的代码进行处理block划分出来train和val的块数量对不上，你知道怎么划分比较合理吗

**Comment by sjtuytc** [comment]
我不太理解对不上是什么意思

**Comment by joeyw1030** [comment]
就是train划分出来3个block 而val只有2个

**Comment by sjtuytc** [comment]
这个关系不是很大吧，就直接follow前人工作就好了，不需要改这个

**Comment by joeyw1030** [comment]
论文中的可见度输出的 是不是就是深度

**Comment by sjtuytc** [comment]
我不知道你说的是哪个论文，这个项目跟原始论文关系不大

**Comment by joeyw1030** [comment]
block-nerf的那篇论文

**Comment by sjtuytc** [comment]
我知道你说的是visibility了，这个不是深度，在这里不回答关于block-nerf论文的问题了

**Comment by sjtuytc** [comment]
关于论文或者general nerf的问题可以到QQ群或者微信群里去问，这里只回答跟本仓库代码有关的问题
