### ISSUE TITLE
请问训练需要的显存占用大概是多少？我训练总是溢出，有办法调整吗？

### ISSUE THREAD

**Issue by lzzppp** [dvlab-research/BlockNeRFPytorch#86]
请问训练需要的显存占用大概是多少？我训练总是溢出，有办法调整吗？

**Comment by sjtuytc** [comment]
3090ti一张，可以调小grid size

**Comment by lzzppp** [comment]
好的。感谢

**Comment by Bin-ze** [comment]
非常感谢您优秀的工作！
我想使用此算法渲染整个楼层的，但是目前遇到一些问题，因此，想向您咨询，主要的问题如下：
1. 拍摄设备的要求，我使用iphone进行了拍摄，但是存在大量抖动，且在走廊的区域，似乎连续帧之间的区别很小，您有构造数据集方面的经验吗？希望可以给点建议
2.  我之前尝试使用instant-ngp对拍摄的小场景（环视的桌子）进行了重建，获得了非常不错的效果，但是当我尝试使用它用于该算法时，我首先取出图像，然后安装您的教程，使用img2pose.py进行了转换，但是出现了错误：
> Mismatch between imgs 0 and poses 69 !!!!
> Below failed files are skip due to SfM failure:
> Too few images...
这个场景一共有69张图像，但似乎转换过程中存在大量的无法匹配
我想了解我应该如何克服这个问题？
3. 我注意到您的教程的第五部分：Build your custom large-scale NeRF 中的第三点：Training NeRF scenes.
里面的命令应该只是一个示例？也就是就算准备了该数据集也是无法运行的，因为它缺少一些必要的参数，还有路径里少了FourierGrid，希望您可以解惑
4. 关于配置：将设我已经构建了整个楼层的场景并获得了相应图像的相机pose，那么我应该使用哪个配置文件开展训练？
5. 您使用3090ti，显存24GB，我目前只有4卡v100,16GB,尝试调节grid size，请问grid size在哪个文件调节？我尝试训练360数据集，但是会在训练的中途OOM。
6. 关于Block-NeRF，我观察到您将在之后的版本移除Block-NeRF的代码，且您的算法与其有相似的属性，但是更快，那么该算法对于大型场景的重建是否可以达到比较不错的效果，您有自己从头构建大型场景并渲染的经验吗？非常期待与您交流

我是NeRF方面的新手，因此可能有一些比较简单的地方未了解清楚，如有叨扰，实感抱歉，感谢您的工作，也期待您的回复！
