### ISSUE TITLE
关于大型真实场景构建与渲染

### ISSUE THREAD

**Issue by Bin-ze** [dvlab-research/BlockNeRFPytorch#87]
非常感谢您优秀的工作！
我想使用此算法渲染整个楼层的办公室场景，但是目前遇到一些问题，因此，想向您咨询，主要的问题如下：
1. 拍摄设备的要求，我使用iphone进行了拍摄，但是存在大量抖动，且在走廊的区域，似乎连续帧之间的区别很小，您有构造数据集方面的经验吗？希望可以给点建议
2.  我之前尝试使用instant-ngp对拍摄的小场景（环视的桌子）进行了重建，获得了非常不错的效果，但是当我尝试使用此数据用于该算法时，我首先取出图像，然后安装您的教程，使用img2pose.py进行了转换，但是出现了错误：
> Mismatch between imgs 0 and poses 69 !!!!
> Below failed files are skip due to SfM failure:
> Too few images...
这个场景一共有69张图像，但似乎转换过程中存在大量的无法匹配。
我想了解我应该如何克服这个问题？
3. 我注意到您的教程的第五部分：Build your custom large-scale NeRF 中的第三点：Training NeRF scenes.
里面的命令应该只是一个示例？也就是就算准备了该数据集也是无法运行的，因为它缺少一些必要的参数，还有路径里似乎少了FourierGrid，希望您可以解惑。
4. 关于配置：假设我已经构建了整个楼层的场景并获得了相应图像的相机pose，那么我应该使用哪个配置文件开展训练？
5. 您使用3090ti，显存24GB，我目前只有4卡v100,16GB,你提到调节grid size可以避免OOM，请问grid size在哪个文件调节？ 我尝试训练360数据集，但是会在训练的中途OOM。
6. 关于Block-NeRF，我观察到您将在之后的版本移除Block-NeRF的代码，且您的算法与其有相似的属性，但是更快，那么该算法对于大型场景的重建是否可以达到比较不错的效果，您有自己从头构建大型场景并渲染的经验吗？非常期待与您交流

我是NeRF方面的新手，因此可能有一些比较简单的地方未了解清楚，如有叨扰，实感抱歉，感谢您的工作，也期待您的回复！

**Comment by Bin-ze** [comment]
我使用380张图像进行pose估计，图像展示的是整个楼层，前后帧之间有一定的重叠，但是花费了大量的时间，最终的结果入下：
<img width="756" alt="image" src="https://user-images.githubusercontent.com/72087870/225868657-4a56c3d1-49d6-4291-9af4-de61a341975c.png">

最终只得到两张未失真的图像。

我不清楚要如何继续开展工作 。。。

**Comment by sjtuytc** [comment]
感谢你的关注和点赞，这对我们非常重要。
最近我会出一个视频，讲如何训练一个新的unbounded NeRF。
1. 构建数据集目前我的经验不多，我只负责COLMAP之后的算法层面的事，从图像采集到COLMAP的过程，包括如何保证高质量的COLMAP，这个不在我的专业范畴 （COLMAP目前社区非常庞大，支持也比较多，因此我暂时不涉足这个领域，关于如何高质量的使用COLMAP，欢迎你参考其他高质量仓库比如nerfstudio等）。
2. 目前CUSTOM scene支持不多，主要原因是1
3. 同2
4. 欢迎看我之后的视频教程，简单的说就是copy一个已有的配置文件，比如nerf_unbounded/room.py，更改一下数据路径，就可以开始训练了。这里主要的技术难点在于效果不理想，如何调试，这也是NeRF的技术核心。我的视频教程主要针对的也是这部分。
5. 搜索voxel_size_density和voxel_size_rgb。
6. 关于Block，我的理解是同一个Block下面比较算法好坏比较有意义，我们实验都是这么做的。当然如果用了block效果会好，这是毫无疑问的。不过目前我更关心的是前者，就是同一个block分化下面去发展一个更好的算法出来。

**Comment by Bin-ze** [comment]
感谢您的回复，我还有一些疑问：
1. 关于我的第三个问题，您的教程是否是有问题的？也就是说您的示例启动程序是无法执行的，因为您已经更新了run_FourierGrid.py的配置。
2.  还有一点，我注意到您参考了https://github.com/sunset1995/DirectVoxGO中的数据处理流程，用于采集自己的场景，并提供了 Madoka and Otobai 的训练配置，但是我尝试使用您提供的代码https://github.com/sjtuytc/LargeScaleNeRFPytorch/blob/main/FourierGrid/tools/imgs2poses.py对 Madoka and Otobai中的图像进行格式转换，转换成功后依然无法训练，报错如下：
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/72087870/226114084-ad3111d7-4d7b-4e6d-8aed-db4e3d2149a2.png">
请问您是否尝试过这些用例，我肯定的是我的步骤是严格依照您的README.md进行的，但是这样的问题却让我很难继续我的研究，您可以帮助我吗？

3. 除了您的算法，我还尝试了其他很多算法，比如mega-nerf等，但是当我阅读论文，并思考其可能的应用场景，我认为mega-nerf本身似乎很难处理大型的室内场景，因为这样的场景与论文的场景有很大的差异，这样的场景拍摄时相机的姿态变化无疑是巨大的，[R,t]矩阵中的t的变化非常大，colmap算法也很难从这样的视频序列中获取稠密的匹配点，我不知道在这样的场景下需要注意何种细节，但是无疑这样的场景是极具挑战的，也是很有现实意义的，这样的重建往往比只在很小的环视场景内构建隐式表示更加有应用场景，您可以给点意见吗？

**Comment by sjtuytc** [comment]
Custom场景暂时不在支持行列了，因为我发现超出了我个人的能力，我们这个仓库更多是为了开发者而服务的，目标是把已有的场景做出最好的效果，而不是支持新场景。如果你确实要做一个新场景，建议你先从NeRFstudio开始跑起，然后再用我们的仓库做优化。我觉得你的分析是有道理的，但是我不确定是不是有助于做你的项目。

**Comment by sjtuytc** [comment]
对了你问的madoka不是unbounded的场景，所以我们后面不支持了，关于做新场景，还是要交由专门的组织去做，我们这里侧重核心算法的优化，不全面支持pipeline。

**Comment by ZhangAma** [comment]
关于unbounded的场景的视频教程，我应该从哪里找到它。

**Comment by sjtuytc** [comment]
还在做素材，视频可能会稍晚出，有好的结果就会放出来

**Comment by Bin-ze** [comment]
我发现我训练360_v2 dataset会在训练途中报显存错误： CUDA out of memory
训练脚本：
> python run_FourierGrid.py --program train --config FourierGrid/configs/nerf_unbounded/room_single.py --num_per_block -1 --eval_ssim --eval_lpips_vgg --render_train --render_test --render_video --exp_id 9

训练过程打印日志：

/home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training
 process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for 
more details.                                                                                                                                                                                                         
  warnings.warn(                                                                                                                                                                                                      
Loading images from ./data/360_v2/room/images_8                                                                                                                                                                       
Loaded image data (259, 389, 3, 311) [259.         389.         396.56617968]                                                                                                                                         
Loaded ./data/360_v2/room 0.1 500.0                                                                                                                                                                                   
/home/guozebin/work_code/LargeScaleNeRFPytorch/FourierGrid/common_data_loaders/load_llff.py:247: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.                       
  R = scipy.spatial.transform.Rotation.align_vectors(                                                                                                                                                                 
Data:                                                                                                                                                                                                                 
(311, 3, 5) (311, 259, 389, 3) (311, 2)                                                                                                                                                                               
HOLDOUT view is 239                                                                                                                                                                                                   
Loaded llff (311, 259, 389, 3) torch.Size([200, 3, 5]) [259.     389.     396.5662] ./data/360_v2/room                                                                                                                
Auto LLFF holdout, 8                                                                                                                                                                                                  
DEFINING BOUNDS                                                                                                                                                                                                       
near_clip 0.019901373982429506                                                                                                                                                                                        
original far 110.56318664550781                                                                                                                                                                                       
NEAR FAR 0 2.290664                                                                                                                                                                                                   
Training: start.                                                                                                                                                                                                      
compute_bbox_by_cam_frustrm: start                                                                                                                                                                                    
  0%|                                                                                                                                                                                         | 0/272 [00:00<?, ?it/s$
/home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Trigger$
d internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)                                                                                                                                                       
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]                                                                                                                                                
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 272/272 [00:00<00:00, 1931.68it/s$
compute_bbox_by_cam_frustrm: xyz_min tensor([-1.1118, -1.0860, -0.8768])                                                                                                                                              
compute_bbox_by_cam_frustrm: xyz_max tensor([1.0794, 1.1052, 1.3144])                                                                                                                                                 
compute_bbox_by_cam_frustrm: finish                                                                                                                                                                                   
train: skip coarse geometry searching                                                                                                                                                                                 
Export bbox and cameras...                                                                                                                                                                                            
compute_bbox_by_cam_frustrm: start                                                                                                                                                                                    
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 272/272 [00:00<00:00, 1970.44it/s$
compute_bbox_by_cam_frustrm: xyz_min tensor([-1.1118, -1.0860, -0.8768])                                                                                                                                              
compute_bbox_by_cam_frustrm: xyz_max tensor([1.0794, 1.1052, 1.3144])                                                                                                                                                 
compute_bbox_by_cam_frustrm: finish                                                                                                                                                                                   
scene_rep_reconstruction (fine): train from scratch                                                                                                                                                                   
create_optimizer_or_freeze_model: param density lr 0.1                                                                                                                                                                
create_optimizer_or_freeze_model: param k0 lr 0.1                                                                                                                                                                     
create_optimizer_or_freeze_model: param rgbnet lr 0.001                                                                                                                                                               
  0%|                                                                                                                                                                                      | 0/100000 [00:00<?, ?it/s$
Using /home/guozebin/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...                                                                                                                                 
Detected CUDA files, patching ldflags                                                                                                                                                                                 
Emitting ninja build file /home/guozebin/.cache/torch_extensions/py39_cu113/segment_cumsum_cuda/build.ninja...                                                                                                        
Building extension module segment_cumsum_cuda...                                                                                                                                                                      
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)                                                                                                     
ninja: no work to do.                                                                                                                                                                                                 
Loading extension module segment_cumsum_cuda...                                                                                                                                                                       
Saved checkpoints at ./logs/360/room_nov25_9/fine_000001.tar                                                                                                                                                          
training iter    500 / Loss: 0.006075587 / PSNR: 19.66 / Eps: 00:00:14
  1%|█▏                                                                                                      1%|█▏
  1%|█▏                                                                                                      1%|█▎
  1%|█▎                                                                                                      1%|█▎
  1%|█▎                                                                                                      1%|█▎
  1%|█▎                                                                                                      1%|█▎
  1%|█▎                                                                                                      1%|█▎
  1%|█▎                                                                                                      1%|█▎
  1%|█▎                                                                                                      1%|█▎
  1%|█▍                                                                                                      1%|█▍
...
FourierGrid: scale_volume_grid finish
training iter   2000 / Loss: 0.008330057 / PSNR: 24.84 / Eps: 00:00:43
training iter   2500 / Loss: 0.003187078 / PSNR: 24.81 / Eps: 00:00:51
training iter   3000 / Loss: 0.003376861 / PSNR: 25.49 / Eps: 00:00:58
training iter   3500 / Loss: 0.002420465 / PSNR: 25.88 / Eps: 00:01:06
  4%|██████▊                                                                                                                                                                    | 3993/100000 [01:11<21:44, 73.60it/s]
FourierGrid: scale_volume_grid finish
training iter   4000 / Loss: 0.005863650 / PSNR: 26.12 / Eps: 00:01:12
training iter   4500 / Loss: 0.002607540 / PSNR: 25.93 / Eps: 00:01:20
training iter   5000 / Loss: 0.002470128 / PSNR: 26.51 / Eps: 00:01:28
training iter   5500 / Loss: 0.002485187 / PSNR: 26.84 / Eps: 00:01:35
  6%|██████████▎                                                                                                                                                                | 5995/100000 [01:41<19:18, 81.15it/s]
FourierGrid: scale_volume_grid finish
training iter   6000 / Loss: 0.004355349 / PSNR: 27.03 / Eps: 00:01:42
training iter   6500 / Loss: 0.002224086 / PSNR: 26.72 / Eps: 00:01:51
training iter   7000 / Loss: 0.002013794 / PSNR: 27.22 / Eps: 00:02:01
training iter   7500 / Loss: 0.001929589 / PSNR: 27.52 / Eps: 00:02:10
  8%|█████████████▋                                                                                                                                                             | 7997/100000 [02:18<29:29, 51.99it/s]
FourierGrid: scale_volume_grid finish
training iter   8000 / Loss: 0.004005897 / PSNR: 27.69 / Eps: 00:02:19
training iter   8500 / Loss: 0.001973804 / PSNR: 27.44 / Eps: 00:02:31
training iter   9000 / Loss: 0.001805447 / PSNR: 27.92 / Eps: 00:02:43
training iter   9500 / Loss: 0.001675683 / PSNR: 28.18 / Eps: 00:02:56
 10%|█████████████████                                                                                                                                                          | 9996/100000 [03:06<33:17, 45.06it/s]
FourierGrid: scale_volume_grid finish
training iter  10000 / Loss: 0.002657533 / PSNR: 28.33 / Eps: 00:03:08
training iter  10500 / Loss: 0.001949108 / PSNR: 28.08 / Eps: 00:03:25
training iter  11000 / Loss: 0.001821517 / PSNR: 28.48 / Eps: 00:03:42
training iter  11500 / Loss: 0.001281528 / PSNR: 28.75 / Eps: 00:03:59
 12%|████████████████████▍                                                                                                                                                     | 11997/100000 [04:15<50:12, 29.22it/s]
FourierGrid: scale_volume_grid finish
training iter  12000 / Loss: 0.002749400 / PSNR: 28.90 / Eps: 00:04:17
training iter  12500 / Loss: 0.001447527 / PSNR: 28.61 / Eps: 00:04:42
training iter  13000 / Loss: 0.001366982 / PSNR: 29.03 / Eps: 00:05:07
training iter  13500 / Loss: 0.001353718 / PSNR: 29.21 / Eps: 00:05:32
 14%|███████████████████████▌                                                                                                                                                | 13997/100000 [05:55<1:12:31, 19.76it/s$
FourierGrid: scale_volume_grid finish
training iter  14000 / Loss: 0.002480254 / PSNR: 29.38 / Eps: 00:05:57
training iter  14500 / Loss: 0.001220357 / PSNR: 29.09 / Eps: 00:06:40
training iter  15000 / Loss: 0.001312725 / PSNR: 29.44 / Eps: 00:07:23
training iter  15500 / Loss: 0.001153118 / PSNR: 29.63 / Eps: 00:08:05
 16%|██████████████████████████▉                                                                                                                                             | 15998/100000 [08:47<2:00:30, 11.62it/s]
FourierGrid: scale_volume_grid finish
training iter  16000 / Loss: 0.002219774 / PSNR: 29.76 / Eps: 00:08:49
 16%|███████████████████████████▏                                                                                                                                              | 16000/100000 [08:48<46:13, 30.29it/s]
Traceback (most recent call last):
  File "/home/guozebin/work_code/LargeScaleNeRFPytorch/run_FourierGrid.py", line 118, in <module>
    run_train(args, cfg, data_dict, export_cam=True, export_geometry=True)
  File "/home/guozebin/work_code/LargeScaleNeRFPytorch/FourierGrid/run_train.py", line 382, in run_train
    psnr = scene_rep_reconstruction(
  File "/home/guozebin/work_code/LargeScaleNeRFPytorch/FourierGrid/run_train.py", line 280, in scene_rep_reconstruction
    loss.backward()
  File "/home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/guozebin/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 2.50 GiB (GPU 0; 15.78 GiB total capacity; 11.43 GiB already allocated; 1.32 GiB free; 13.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated
memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

观察到的现象：
训练开始：显存占用只有1700M，随着step的增加，显存指数上升，当训练到整个过程的16%，显存爆炸，这是正常的嘛，我认为代码中肯定存在哪些变量，随着训练strp的增加，不断增大，且不会在训练中途释放，您可以告诉我应该怎样解决这样的问题吗

**Comment by sjtuytc** [comment]
16000会放大二倍，你可以调整这个参数，搜索16000即可，在config里面有scale这个参数

**Comment by Bin-ze** [comment]
我已经成功将算法用于真实场景，但是效果一般，我有几处问题想向您请教：
1. 您指出在step=16000网络大小会放大二倍，这里的step与精度的关系是怎样的？
2. 为了保证算法在v100上正常运行，我修改了voxel_size_density = 150  # default 400
voxel_size_rgb = 150，您能告诉我这些参数与精度的关系吗？
3. 使用--render-vedio时，使用的pose是否来自训练集？

**Comment by sjtuytc** [comment]
我们论文里有ablation study，不过这些参数仍然是合适就是最好的，就是试出来的

**Comment by sjtuytc** [comment]
Render video使用的是render集合，没有gt，不是Train也不是test

**Comment by Bin-ze** [comment]
好的，非常感谢，我还想问下，你们的算法训练的是一个nerf还是多个？

**Comment by sjtuytc** [comment]
在waymo上是多个，其余的是一个

**Comment by Bin-ze** [comment]
我尝试使用polycam数据生成你的算法所需要的llff格式，我查看了代码，llff需要一个poses_bounds.npy来指示相机pose，其是一个17维的向量，其中的前15维分别为相机的内外参，可以获取，但是最后两维表示图像的最近、最远深度界限，我不只如何在不使用colmap的稀疏点云的前提下获取他们，因此我尝试根据经验，固定它们的值，但是毫无疑问，效果很差，我不知道发生了什么，您的代码中关于near，far的部分因为没有注释的原因，几乎看不懂它表示了什么，而且据我观察，这应该是一个软约束，也就是说根据经验调节与根据点云计算其实不会导致过大的误差，只要保证你的经验是可靠的，您有这方面的经验吗？我希望得到您的帮助

**Comment by sjtuytc** [comment]
目前看起来这两个参数重要性不大

**Comment by Bin-ze** [comment]
我查看了数据处理部分以及模型部分，我发现这两个参数根本没有用到，是这样吗

**Comment by sjtuytc** [comment]
是的几乎没用在我们这里

**Comment by Bin-ze** [comment]
> 在waymo上是多个，其余的是一个

我有点不能理解，为什么在waymo数据集上会是多个nerf，而其他数据集上是一个，是因为针对waymo数据集，您使用了blocknerf中的策略吗？那在其他数据集上可以划分不同的block吗？隐式的划分而非在定义数据集时就指定

**Comment by sjtuytc** [comment]
可以这么理解，具体得看我们的论文了

**Comment by Bin-ze** [comment]
> parser.add_argument("--num_per_block", type=int, default=-1,
                        help='Number of images per block. Set to -1 to forbid block training.')

我想问一下这个参数是不是用来指定block-nerf的个数的？

**Comment by sjtuytc** [comment]
是的

**Comment by Bin-ze** [comment]
这样说的话不就与您前面所提到的“在waymo上是多个，其余的是一个”相矛盾了，还是说在其他数据集上可以设置为1个nerf训练，也可以设置为多个nerf训练？

**Comment by sjtuytc** [comment]
有这个开关但是其他数据集并不支持

**Comment by wtj-zhong** [comment]
i used  ：
python run_FourierGrid.py --program train --config FourierGrid/configs/tankstemple_unbounded/playground_single.py --num_per_block -1 --render_train --render_test --render_video --exp_id 57
 and i get： Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.50 GiB (GPU 0; 15.74 GiB total capacity; 11.33 GiB already allocated; 2.04 GiB free; 12.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
how i do something solve this problem

**Comment by tang-hy** [comment]
> 可以这么理解，具体得看我们的论文了

May I ask when your paper will be released
