### ISSUE TITLE
What does time required for "Exhaustive Feature Matching" depend on during "imgs2poses"

### ISSUE THREAD

**Issue by tahsinmocdt** [dvlab-research/BlockNeRFPytorch#88]
I am trying to run the "imgs2poses" on a total of 167 images taken as frames from a video. This is a circular video of an outdoor basketball court with some outdoor scenes such as houses and cars. The dimensions of the images are 1920*1080p. In the Feature Extraction phase of the "imgs2poses", there are 10k-13k features per image on average. 

Now my question is, the "Exhaustive Feature Matching" phase has been running for 2 hours almost and is still on "Matching block [1/4, 1/4], same as when it started.  I'm afraid to stop the process midway. So I have to ask, is this normal? Should I wait? Is convergence guaranteed? Can you please give some pointers from experience if this is normal? Thanks.

**Comment by sjtuytc** [comment]
It's normal, and COLMAP implements this algorithm. You need to visit COLMAP's official repo for more support. You can also use NeRFstudio to generate poses.

**Comment by tahsinmocdt** [comment]
Is it possible to train the model for Sequential Feature Matching using the current repo?

**Comment by sjtuytc** [comment]
I'm not sure whether I understand you but I did not try this before.
