### ISSUE TITLE
Is there any script that supports arbitrary viewing angle rendering?

### ISSUE THREAD

**Issue by Bin-ze** [dvlab-research/BlockNeRFPytorch#89]
I noticed that your repo is only developed for research, so when evaluating the effect, it just reads the image and the corresponding pose from the test set to render the image and evaluate the result, but there is no script to support the rendering from the selected perspective , Is there a plan to support it?

**Comment by sjtuytc** [comment]
Thanks for your attention. We have a render split where the gt is not available. Render split is different from test split because render split does not have the gt. You can replace the cameras in the render split and infer via render video option. This setup is consistent with DVGOv2.

**Comment by Bin-ze** [comment]
I hope I can help you improve this part of the code. My idea is to use the test set as the key frame on the rendering path, and then use smoothing means to arbitrarily add poses between the key frames, so as to achieve rendering at any angle and at any fps

**Comment by sjtuytc** [comment]
Yes you hit a meaningful point. This function you proposed can be regarded as a interpolation method to generate renderings. In fact, it is hard to generate reliable interpolation of view points. Also, it is not far enough from the training views. 
We are working on importing and exporting views with the nerfstudio platform. This way seems to be a better solution.

**Comment by Bin-ze** [comment]
good job! I also want to know the details about your algorithm implementation, when will your paper be uploaded?

**Comment by sjtuytc** [comment]
It is hard to say a specific date. We are still progressing.
