### ISSUE TITLE
在跑tanks and temples数据集上的一些问题

### ISSUE THREAD

**Issue by zl264** [dvlab-research/BlockNeRFPytorch#90]
您好，我是NeRF初学者，在tanks and temples数据集上跑您代码中的FourierGrid时有一些疑惑：
1. 在M60场景中，训练集上的PSNR只有26，测试集上的PSNR只能达到18；在Train场景中，训练集上的PSNR只有23，测试集上的PSNR也是只能达到18。在训练过程中，使用的是您提供的预处理的tanks and temples数据集。训练命令为：
python run_FourierGrid.py --program train --config FourierGrid/configs/tankstemple_unbounded/train_single.py --num_per_block -1 --render_train --render_test --render_video --exp_id 12
python run_FourierGrid.py --program train --config FourierGrid/configs/tankstemple_unbounded/m60_single.py --num_per_block -1 --render_train --render_test --render_video --exp_id 6
其中只是修改了配置文件中的datadir。
对于上述得到的训练结果，PSNR这么低是因为我跑错了还是这就是这个数据集的SOTA水平了。
2. 我大致看了您的FourierGrid模型代码，没有进行分块，基本上就是DVGO模型的流程(只是跳过了Coarse部分)，不知道我是否遗漏了哪些地方没有看到，希望您能够指正。
非常期望您能够回复，谢谢！

**Comment by sjtuytc** [comment]
1.这是不应该的，你有没有更改过其他的参数，然后运行环境和截图提供一下。
2.我们的工作不进行分块，或者说这并不是我们的贡献。

**Comment by zl264** [comment]
> 

我是在3090上跑的，没有修改过其他参数，不知道你需要哪方面的截图呢

**Comment by sjtuytc** [comment]
运行log

**Comment by sjtuytc** [comment]
训练过程输出，还有最后产生的render video

**Comment by zl264** [comment]
已经通过邮件发送给你了

**Comment by sjtuytc** [comment]
收到，我查对了我的原始实验记录，你的实验结果跟我的原始记录是一致的，
![image](https://user-images.githubusercontent.com/31123348/226545695-3054099f-5fc0-44a7-a7bc-d85ed215c558.png)

平均分跟代码库首页是对的上的，这个场景只能这么高了，我尽力调了

**Comment by zl264** [comment]
> 收到，我查对了我的原始实验记录，你的实验结果跟我的原始记录是一致的， ![image](https://user-images.githubusercontent.com/31123348/226545695-3054099f-5fc0-44a7-a7bc-d85ed215c558.png)
> 
> 平均分跟代码库首页是对的上的，这个场景只能这么高了，我尽力调了

**Comment by zl264** [comment]
好的，谢谢！

**Comment by sjtuytc** [comment]
另外你不需要发邮件，github本身支持发log和视频，再次感谢你对本仓库的支持和对社区可复现性的贡献。

**Comment by zl264** [comment]
好的，我多研究一下GitHub的功能。
