### ISSUE TITLE
在waymo数据集上运行FourierGrid模型，

### ISSUE THREAD

**Issue by zl264** [dvlab-research/BlockNeRFPytorch#91]
1. 我根据您的[文档](https://github.com/sjtuytc/UnboundedNeRFPytorch/blob/main/docs/get_pytorch_waymo_dataset.md)处理了waywo数据集，其他部分和您在README.md中提到的文件目录结构一致，就是train目录中val目录中分别多了train_all_meta.pt文件和val_all_meta.pt文件
![image](https://user-images.githubusercontent.com/52619637/226552041-0dc0a974-d34e-42a9-9e6d-8b35037525e6.png)
![image](https://user-images.githubusercontent.com/52619637/226552218-967627ee-cb2f-4c9d-a56f-3877856f369e.png)
![image](https://user-images.githubusercontent.com/52619637/226554438-b43fc1c0-cccc-42cf-9c4c-6e33704cf40d.png)
使用命令进行训练：
```python run_FourierGrid.py --program train --config FourierGrid/configs/waymo/waymo_no_block.py --num_per_block 100 --render_video --exp_id 30```
然后报错：
```
Traceback (most recent call last):
  File "run_FourierGrid.py", line 97, in <module>
    data_dict, args = load_everything(args=args, cfg=cfg)
  File "/mnt/nas_8/group/zenglin/nerf/LargeScaleNeRFPytorch/FourierGrid/load_everything.py", line 15, in load_everything
    data_dict = load_waymo_data(args, cfg)
  File "/mnt/nas_8/group/zenglin/nerf/LargeScaleNeRFPytorch/FourierGrid/load_waymo.py", line 398, in load_waymo_data
    images, poses, render_poses, HW, K, cam_idxs, i_split = load_waymo(args, cfg)
  File "/mnt/nas_8/group/zenglin/nerf/LargeScaleNeRFPytorch/FourierGrid/load_waymo.py", line 267, in load_waymo
    with open(os.path.join(basedir, f'metadata.json'), 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: './datasets/pytorch_waymo_dataset/metadata.json'
```
可以发现，处理后的waymo数据集确实没有metadata.json文件，请问这该如何处理呢
2. 在处理waymo数据集时，运行data_preprocess/split_block.py时报错：
```
Traceback (most recent call last):
  File "split_block.py", line 285, in <module>
    train_origins = extract_origins(train_meta)
  File "split_block.py", line 204, in extract_origins
    origins = np.array(origins)
ValueError: only one element tensors can be converted to Python scalars
```
通过将204行的```origins = np.array(origins)```改成```origins = torch.cat(origins, dim=0).reshape((-1, 3))```解决。

非常希望您能够回复，谢谢！

**Comment by sjtuytc** [comment]
Waymo数据集pose有问题，特别是距离比较长的，所以我最近没在做了，准备找个更好的数据集做。我之后帮你看一下具体情况。我记得你需要执行一个merge的文件把trainval的meta合起来，你可以搜一下metadata.json在哪里出现，就知道怎么弄了。

**Comment by zl264** [comment]
好的，谢谢！

**Comment by zl264** [comment]
我找到了comvog_organize_by_cam_pos.py文件，看上去比较像您描述的

**Comment by zl264** [comment]
> Waymo数据集pose有问题，特别是距离比较长的，所以我最近没在做了，准备找个更好的数据集做。我之后帮你看一下具体情况。我记得你需要执行一个merge的文件把trainval的meta合起来，你可以搜一下metadata.json在哪里出现，就知道怎么弄了。

 



您好，我按照您的`waymo_no_block.py`配置文件跑了waymo数据集，在训练集上得到的结果如下所示：

https://user-images.githubusercontent.com/52619637/226777730-851887f5-4fda-4c87-8c36-1084bafe1fe4.mp4


在训练集上生成的视频看上去还行，但是最后render_video得到的结果在视角转了一个角度后就得到了一个很糟糕的结果，如下所示：

https://user-images.githubusercontent.com/52619637/226777057-e6f1bd09-3544-4693-bb7d-72a92295d81e.mp4

这是否就是您说的Waymo数据集pose有问题

**Comment by sjtuytc** [comment]
是的，首先我发现不同相机之间没有很好的对准，差个5度算是很常见的，就算是同一个相机，前后帧之间也没有很好的对齐。如果你对原始图像序列使用一下colmap就知道了，colmap对这种图像序列不好work.

**Comment by zl264** [comment]
好的，谢谢！

**Comment by 834810269** [comment]
Hi @zl264 我也在waymo数据集上尝试训练FourierGrid，但是无法复现你渲染出的效果，想请教下：
1.你的配置就是默认的waymo_no_block.py 吗，或者代码内有没有做什么调整
2.你有没有使用多block训练，有没有对waymo数据集做其他处理？

**Comment by zl264** [comment]
> Hi @zl264 我也在waymo数据集上尝试训练FourierGrid，但是无法复现你渲染出的效果，想请教下： 1.你的配置就是默认的waymo_no_block.py 吗，或者代码内有没有做什么调整 2.你有没有使用多block训练，有没有对waymo数据集做其他处理？

原来配置文件中训练步骤是3000，我改成30000了，其他地方没有改变

**Comment by 834810269** [comment]
> 

你训练的是哪个block数据？

**Comment by zl264** [comment]
> > 
> 
> 你训练的是哪个block数据？

waymo_no_block.py指定的那50张图

**Comment by 834810269** [comment]
> 

谢谢，我去看看

**Comment by Xiao-Rou** [comment]
> comvog_organize_by_cam_pos.py

你好，我遇到了一样的找不到文件的问题，我想请教一下该怎么解决

**Comment by zl264** [comment]
> comvog_organize_by_cam_pos.py

你需要先运行comvog_organize_by_cam_pos.py生成那个json文件

**Comment by Xiao-Rou** [comment]
打扰了大佬，能再讲细一点吗，纯小白❤

**Comment by zl264** [comment]
> 打扰了大佬，能再讲细一点吗，纯小白❤

我也是小白，你按照这个[文档](https://github.com/sjtuytc/UnboundedNeRFPytorch/blob/main/docs/get_pytorch_waymo_dataset.md)的步骤生成数据集，但是这个文档少了一步，就是少了要运行comvog_organize_by_cam_pos.py这个文件

**Comment by Xiao-Rou** [comment]
好的谢谢咯我去试试

**Comment by mabaorui** [comment]
> 1. 我根据您的[文档](https://github.com/sjtuytc/UnboundedNeRFPytorch/blob/main/docs/get_pytorch_waymo_dataset.md)处理了waywo数据集，其他部分和您在README.md中提到的文件目录结构一致，就是train目录中val目录中分别多了train_all_meta.pt文件和val_all_meta.pt文件
>    ![image](https://user-images.githubusercontent.com/52619637/226552041-0dc0a974-d34e-42a9-9e6d-8b35037525e6.png)
>    ![image](https://user-images.githubusercontent.com/52619637/226552218-967627ee-cb2f-4c9d-a56f-3877856f369e.png)
>    ![image](https://user-images.githubusercontent.com/52619637/226554438-b43fc1c0-cccc-42cf-9c4c-6e33704cf40d.png)
>    使用命令进行训练：
>    `python run_FourierGrid.py --program train --config FourierGrid/configs/waymo/waymo_no_block.py --num_per_block 100 --render_video --exp_id 30`
>    然后报错：
> 
> ```
> Traceback (most recent call last):
>   File "run_FourierGrid.py", line 97, in <module>
>     data_dict, args = load_everything(args=args, cfg=cfg)
>   File "/mnt/nas_8/group/zenglin/nerf/LargeScaleNeRFPytorch/FourierGrid/load_everything.py", line 15, in load_everything
>     data_dict = load_waymo_data(args, cfg)
>   File "/mnt/nas_8/group/zenglin/nerf/LargeScaleNeRFPytorch/FourierGrid/load_waymo.py", line 398, in load_waymo_data
>     images, poses, render_poses, HW, K, cam_idxs, i_split = load_waymo(args, cfg)
>   File "/mnt/nas_8/group/zenglin/nerf/LargeScaleNeRFPytorch/FourierGrid/load_waymo.py", line 267, in load_waymo
>     with open(os.path.join(basedir, f'metadata.json'), 'r') as fp:
> FileNotFoundError: [Errno 2] No such file or directory: './datasets/pytorch_waymo_dataset/metadata.json'
> ```
> 
> 可以发现，处理后的waymo数据集确实没有metadata.json文件，请问这该如何处理呢 2. 在处理waymo数据集时，运行data_preprocess/split_block.py时报错：
> 
> ```
> Traceback (most recent call last):
>   File "split_block.py", line 285, in <module>
>     train_origins = extract_origins(train_meta)
>   File "split_block.py", line 204, in extract_origins
>     origins = np.array(origins)
> ValueError: only one element tensors can be converted to Python scalars
> ```
> 
> 通过将204行的`origins = np.array(origins)`改成`origins = torch.cat(origins, dim=0).reshape((-1, 3))`解决。
> 
> 非常希望您能够回复，谢谢！

@zl264 
您好，可以分享metadata.json文件吗？谢谢

**Comment by zl264** [comment]
> 

请问要怎么给你

**Comment by mabaorui** [comment]
> > 
> 
> 请问要怎么给你

@zl264 非常感谢！邮箱或者网盘都可以，我的邮箱是 mbr18@mails.tsinghua.edu.cn

**Comment by cnu-Dawn** [comment]
可以给我发一份json吗

**Comment by cnu-Dawn** [comment]
邮箱1132408661@qq.com

**Comment by KnightOfTheMoonlight** [comment]
> 是的，首先我发现不同相机之间没有很好的对准，差个5度算是很常见的，就算是同一个相机，前后帧之间也没有很好的对齐。如果你对原始图像序列使用一下colmap就知道了，colmap对这种图像序列不好work.

@sjtuytc  Hi, I tried to run your 
[run_sfm.py](https://github.com/sjtuytc/UnboundedNeRFPytorch/blob/main/FourierGrid/run_sfm.py) script. But it looks uncomplete.

Could you complete this?

**Comment by sjtuytc** [comment]
It's not used in our repo.

**Comment by sjtuytc** [comment]
> > 是的，首先我发现不同相机之间没有很好的对准，差个5度算是很常见的，就算是同一个相机，前后帧之间也没有很好的对齐。如果你对原始图像序列使用一下colmap就知道了，colmap对这种图像序列不好work.
> 
> 
> 
> @sjtuytc  Hi, I tried to run your 
> 
> [run_sfm.py](https://github.com/sjtuytc/UnboundedNeRFPytorch/blob/main/FourierGrid/run_sfm.py) script. But it looks uncomplete.
> 
> 
> 
> Could you complete this?
