### ISSUE TITLE
About opacity of per piexl

### ISSUE THREAD

**Issue by szgy66** [dvlab-research/BlockNeRFPytorch#93]
Hello researcher, thank you for your great work. I have reproduced your project well on my own data set. Save the relevant RGB and depth of the video. Recently, I have been working on converting the generated results into 3Dmesh. I get inspired by [that](https://github.com/kwea123/nerf_pl/blob/master/extract_color_mesh.py) which uses the opacity generated by the model for subsequent operations. But she's based on light and gets the opacity per pixel, but your project is based on voxels. So for your project, how should I get the opacity of each pixel better? Do you have any good suggestions? Thanks!

**Comment by sjtuytc** [comment]
Thanks for your attention and appreciation. Unfortunately I don't have any experiences in mesh generation. I cannot help you at this moment.
