### ISSUE TITLE
No module named'adam_upd_cuda'

### ISSUE THREAD

**Issue by ghaodong** [dvlab-research/BlockNeRFPytorch#94]
您好，在跑waymo数据集时报错，说No module named'adam_upd_cuda',  也就是在masked_adam.py第三行没导入进来，这个怎么解决呀？麻烦您了

**Comment by sjtuytc** [comment]
感谢你的关注，编译了吗？

**Comment by ghaodong** [comment]
您好，上面那个问题确实是没有编译的问题，然后我现在在训练完以后模型文件的保存出问题了，我试了在迭代一轮后都可以render出视频的，然后我在train1w轮后，模型权重保存就出错了 
![1679806702970](https://user-images.githubusercontent.com/115460758/227756345-07b7c685-3e86-4ad2-9b72-37d46866365b.jpg)

**Comment by sjtuytc** [comment]
这个应该是本地文件系统的问题，比如不允许写入，或者内存满了

**Comment by hugege1123** [comment]
你好，我是windows系统，如何编译？什么工具如何编译？

**Comment by sjtuytc** [comment]
装wsl，然后就跟linux一样了
