### ISSUE TITLE
可以在Win系统下运行吗

### ISSUE THREAD

**Issue by Xiao-Rou** [dvlab-research/BlockNeRFPytorch#95]

**Comment by sjtuytc** [comment]
Windows下装个wsl就跟linux一样了，很好用

**Comment by Xiao-Rou** [comment]
好的谢谢，我去试一试

**Comment by Xiao-Rou** [comment]
打扰了，我还想请教一下我现在是wsl的环境配置，但是from pytorch_lightning.plugins import DDPPlugin中的DDPPlugin仍是标红报错，想问一下该怎解决呢

**Comment by sjtuytc** [comment]
库没有装好吧，你谷歌一下
