### ISSUE TITLE
How fast is FourierGrid compared with mipnerf360?

### ISSUE THREAD

**Issue by CSU-NXY** [dvlab-research/BlockNeRFPytorch#96]
Hi, thanks for your great work! 

I noticed that the grid-based method is stated to be fast and simple in readme. Have you compared the training speed of FourierGrid and other method like mipnerf360?

**Comment by sjtuytc** [comment]
Thanks for your attention.
theoretically, fouriergrid should be relatively faster because it does not use a large MLP. However, We do not extensively optimize our code.
