### ISSUE TITLE
将block-nerf拓展到真实场景需要注意什么？

### ISSUE THREAD

**Issue by Bin-ze** [dvlab-research/BlockNeRFPytorch#97]
我想要将您所复现的block-nerf拓展到真实的使用场景，请问我应该做哪些工作？我需要注意哪些问题呢？

**Comment by sjtuytc** [comment]
Block NeRF只提供一个缩小问题规模的工具，但是对于真实场景，面临的问题仍然是复杂多样的。没有具体问题定位的话，我恐怕给不出有用的建议。

**Comment by Bin-ze** [comment]
因为单个nerf的容量有限，很难建模大场景，因此我想使用block-nerf来建模整个楼层(50x50m左右，且包含走廊，房间以及公共区域等)，我在思考如何使用block-nerf缩小问题的规模，从而可以从局部到整体。

**Comment by sjtuytc** [comment]
这是个自然的想法，然而不一定是根本问题

**Comment by Bin-ze** [comment]
对于这样的场景，您认为单个nerf是否可行？如果可行的话，应该注意哪些建模细节(比如增加网络的容量，边界条件等等，拍摄角度以及数量等等)？使用block-nerf是否是一种更好的办法？大场景建模失败的根本问题又在哪里呢？

**Comment by sjtuytc** [comment]
不做很难知道

**Comment by Bin-ze** [comment]
实际上我已经尝试了多个sota的nerf算法，在大场景下他们都不work，因此block-nerf可能是必须要尝试的选择

**Comment by sjtuytc** [comment]
是的可以尝试
