### ISSUE TITLE
waymo数据集下载

### ISSUE THREAD

**Issue by Bin-ze** [dvlab-research/BlockNeRFPytorch#98]
作者，您好！
我想要下载waymo数据集以方便训练block-nerf，但是使用google网盘下载会因为网络原因而出错，请问您有其他链接地址吗，比如百度网盘等

**Comment by sjtuytc** [comment]
没有，百度网盘太慢了。科学上网可以。

**Comment by Bin-ze** [comment]
。。。，好的，谢谢了
